/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 * vim: set ts=8 sts=2 et sw=2 tw=80:
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef jit_ABIFunctionList_inl_h
#define jit_ABIFunctionList_inl_h

#include "mozilla/MacroArgs.h"  // MOZ_CONCAT
#include "mozilla/SIMD.h"       // mozilla::SIMD::memchr{,2x}{8,16}

#include "jslibmath.h"  // js::NumberMod
#include "jsmath.h"     // js::ecmaPow, js::ecmaHypot, js::hypot3, js::hypot4,
                        // js::ecmaAtan2, js::UnaryMathFunctionType, js::powi
#include "jsnum.h"      // js::StringToNumberPure, js::Int32ToStringPure,
                        // js::NumberToStringPure

#include "builtin/Array.h"             // js::ArrayShiftMoveElements
#include "builtin/MapObject.h"         // js::MapIteratorObject::next,
                                       // js::SetIteratorObject::next
#include "builtin/Object.h"            // js::ObjectClassToString
#include "builtin/RegExp.h"            // js::RegExpPrototypeOptimizableRaw,
                                       // js::RegExpInstanceOptimizableRaw
#include "builtin/Sorting.h"           // js::ArraySortData
#include "builtin/TestingFunctions.h"  // js::FuzzilliHash*
#include "builtin/WeakMapObject.h"     // js::WeakMapObject::{get,has}Object
#include "builtin/WeakSetObject.h"     // js::WeakSetObject::hasObject
#include "irregexp/RegExpAPI.h"
// js::irregexp::CaseInsensitiveCompareNonUnicode,
// js::irregexp::CaseInsensitiveCompareUnicode,
// js::irregexp::GrowBacktrackStack,
// js::irregexp::IsCharacterInRangeArray

#include "jit/ABIFunctions.h"
#include "jit/Bailouts.h"  // js::jit::FinishBailoutToBaseline, js::jit::Bailout,
                           // js::jit::InvalidationBailout

#include "jit/Ion.h"          // js::jit::LazyLinkTopActivation
#include "jit/JitFrames.h"    // HandleException
#include "jit/VMFunctions.h"  // Rest of js::jit::* functions.

#include "js/CallArgs.h"     // JSNative
#include "js/Conversions.h"  // JS::ToInt32
// JSJitGetterOp, JSJitSetterOp, JSJitMethodOp
#include "js/experimental/JitInfo.h"

#include "proxy/Proxy.h"  // js::ProxyGetProperty

#include "vm/ArgumentsObject.h"   // js::ArgumentsObject::finishForIonPure
#include "vm/Interpreter.h"       // js::TypeOfObject
#include "vm/NativeObject.h"      // js::NativeObject
#include "vm/RegExpShared.h"      // js::ExecuteRegExpAtomRaw
#include "vm/TypedArrayObject.h"  // js::TypedArraySortFromJit
#include "wasm/WasmBuiltins.h"    // js::wasm::*

#include "builtin/Boolean-inl.h"  // js::EmulatesUndefined

namespace js {

namespace wasm {

class AnyRef;

}  // namespace wasm

namespace jit {

// List of all ABI functions to be used with callWithABI. Each entry stores
// the fully qualified name of the C++ function. This list must be sorted.
#if JS_GC_PROBES
#  define ABIFUNCTION_JS_GC_PROBES_LIST(_) _(js::jit::TraceCreateObject)
#else
#  define ABIFUNCTION_JS_GC_PROBES_LIST(_)
#endif

#if defined(JS_CODEGEN_ARM)
#  define ABIFUNCTION_JS_CODEGEN_ARM_LIST(_) \
    _(__aeabi_idivmod)                       \
    _(__aeabi_uidivmod)
#else
#  define ABIFUNCTION_JS_CODEGEN_ARM_LIST(_)
#endif

#ifdef WASM_CODEGEN_DEBUG
#  define ABIFUNCTION_WASM_CODEGEN_DEBUG_LIST(_) \
    _(js::wasm::PrintF32)                        \
    _(js::wasm::PrintF64)                        \
    _(js::wasm::PrintI32)                        \
    _(js::wasm::PrintPtr)                        \
    _(js::wasm::PrintText)
#else
#  define ABIFUNCTION_WASM_CODEGEN_DEBUG_LIST(_)
#endif

#ifdef FUZZING_JS_FUZZILLI
#  define ABIFUNCTION_FUZZILLI_LIST(_) _(js::FuzzilliHashBigInt)
#else
#  define ABIFUNCTION_FUZZILLI_LIST(_)
#endif

// List of all ABI functions and their linker symbols used with callWithABI in
// the context of CacheIR compilation. Assembly generated by spasm uses these
// symbols to refer to the functions.
#if JS_GC_PROBES
#  define ABIFUNCTION_AND_SYMBOL_JS_GC_PROBES_LIST(_) \
    _(js::jit::TraceCreateObject, TraceCreateObject)
#else
#  define ABIFUNCTION_AND_SYMBOL_JS_GC_PROBES_LIST(_)
#endif

#if defined(JS_CODEGEN_ARM)
#  define ABIFUNCTION_AND_SYMBOL_JS_CODEGEN_ARM_LIST(_) \
    _(__aeabi_idivmod, __aeabi_idivmod)                 \
    _(__aeabi_uidivmod, __aeabi_uidivmod)
#else
#  define ABIFUNCTION_AND_SYMBOL_JS_CODEGEN_ARM_LIST(_)
#endif

#ifdef WASM_CODEGEN_DEBUG
#  define ABIFUNCTION_AND_SYMBOL_WASM_CODEGEN_DEBUG_LIST(_) \
    _(js::wasm::PrintF32, PrintF32)                         \
    _(js::wasm::PrintF64, PrintF64)                         \
    _(js::wasm::PrintI32, PrintI32)                         \
    _(js::wasm::PrintPtr, PrintPtr)                         \
    _(js::wasm::PrintText, PrintText)
#else
#  define ABIFUNCTION_AND_SYMBOL_WASM_CODEGEN_DEBUG_LIST(_)
#endif

#ifdef FUZZING_JS_FUZZILLI
#  define ABIFUNCTION_AND_SYMBOL_FUZZILLI_LIST(_) \
    _(js::FuzzilliHashBigInt, FuzzilliHashBigInt)
#else
#  define ABIFUNCTION_AND_SYMBOL_FUZZILLI_LIST(_)
#endif

#define ABIFUNCTION_LIST(_)                                                    \
  ABIFUNCTION_JS_GC_PROBES_LIST(_)                                             \
  ABIFUNCTION_JS_CODEGEN_ARM_LIST(_)                                           \
  ABIFUNCTION_WASM_CODEGEN_DEBUG_LIST(_)                                       \
  _(js::ArgumentsObject::finishForIonPure)                                     \
  _(js::ArgumentsObject::finishInlineForIonPure)                               \
  _(js::ArrayShiftMoveElements)                                                \
  _(js::ArraySortData::sortArrayWithComparator)                                \
  _(js::ArraySortData::sortTypedArrayWithComparator)                           \
  _(js::ArraySortFromJit)                                                      \
  _(js::ecmaAtan2)                                                             \
  _(js::ecmaHypot)                                                             \
  _(js::ecmaPow)                                                               \
  _(js::EmulatesUndefined)                                                     \
  _(js::EmulatesUndefinedCheckFuse)                                            \
  _(js::ExecuteRegExpAtomRaw)                                                  \
  _(js::hypot3)                                                                \
  _(js::hypot4)                                                                \
  _(js::Interpret)                                                             \
  _(js::Int32ToStringPure)                                                     \
  _(js::irregexp::CaseInsensitiveCompareNonUnicode)                            \
  _(js::irregexp::CaseInsensitiveCompareUnicode)                               \
  _(js::irregexp::GrowBacktrackStack)                                          \
  _(js::irregexp::IsCharacterInRangeArray)                                     \
  _(js::jit::AllocateAndInitTypedArrayBuffer)                                  \
  _(js::jit::AllocateBigIntNoGC)                                               \
  _(js::jit::AllocateFatInlineString)                                          \
  _(js::jit::AllocateDependentString)                                          \
  _(js::jit::AssertMapObjectHash)                                              \
  _(js::jit::AssertPropertyLookup)                                             \
  _(js::jit::AssertSetObjectHash)                                              \
  _(js::jit::AssertValidBigIntPtr)                                             \
  _(js::jit::AssertValidObjectPtr)                                             \
  _(js::jit::AssertValidStringPtr)                                             \
  _(js::jit::AssertValidSymbolPtr)                                             \
  _(js::jit::AssertValidValue)                                                 \
  _(js::jit::AssumeUnreachable)                                                \
  _(js::jit::AtomicsStore64)                                                   \
  _(js::jit::AtomizeStringNoGC)                                                \
  _(js::jit::Bailout)                                                          \
  _(js::jit::BigIntNumberEqual<js::jit::EqualityKind::Equal>)                  \
  _(js::jit::BigIntNumberEqual<js::jit::EqualityKind::NotEqual>)               \
  _(js::jit::BigIntNumberCompare<js::jit::ComparisonKind::LessThan>)           \
  _(js::jit::NumberBigIntCompare<js::jit::ComparisonKind::LessThan>)           \
  _(js::jit::NumberBigIntCompare<js::jit::ComparisonKind::GreaterThanOrEqual>) \
  _(js::jit::BigIntNumberCompare<js::jit::ComparisonKind::GreaterThanOrEqual>) \
  _(js::jit::DateFillLocalTimeSlots)                                           \
  _(js::jit::EqualStringsHelperPure)                                           \
  _(js::jit::FinishBailoutToBaseline)                                          \
  _(js::jit::Float16ToFloat32)                                                 \
  _(js::jit::Float32ToFloat16)                                                 \
  _(js::jit::FrameIsDebuggeeCheck)                                             \
  _(js::jit::GetContextSensitiveInterpreterStub)                               \
  _(js::jit::GetIndexFromString)                                               \
  _(js::jit::GetInt32FromStringPure)                                           \
  _(js::jit::GetNativeDataPropertyPure)                                        \
  _(js::jit::GetNativeDataPropertyPureWithCacheLookup)                         \
  _(js::jit::GetNativeDataPropertyByValuePure)                                 \
  _(js::jit::GlobalHasLiveOnDebuggerStatement)                                 \
  _(js::jit::HandleCodeCoverageAtPC)                                           \
  _(js::jit::HandleCodeCoverageAtPrologue)                                     \
  _(js::jit::HandleException)                                                  \
  _(js::jit::HasNativeDataPropertyPure<false>)                                 \
  _(js::jit::HasNativeDataPropertyPure<true>)                                  \
  _(js::jit::HasNativeElementPure)                                             \
  _(js::jit::InitBaselineFrameForOsr)                                          \
  _(js::jit::InvalidationBailout)                                              \
  _(js::jit::InvokeFromInterpreterStub)                                        \
  _(js::jit::LazyLinkTopActivation)                                            \
  _(js::jit::LinearizeForCharAccessPure)                                       \
  _(js::jit::ObjectHasGetterSetterPure)                                        \
  _(js::jit::ObjectIsCallable)                                                 \
  _(js::jit::ObjectIsConstructor)                                              \
  _(js::jit::PostGlobalWriteBarrier)                                           \
  _(js::jit::PostWriteBarrier)                                                 \
  _(js::jit::PostWriteElementBarrier)                                          \
  _(js::jit::PreserveWrapper)                                                  \
  _(js::jit::Printf0)                                                          \
  _(js::jit::Printf1)                                                          \
  _(js::jit::StringFromCharCodeNoGC)                                           \
  _(js::jit::StringTrimEndIndex)                                               \
  _(js::jit::StringTrimStartIndex)                                             \
  _(js::jit::TypeOfNameObject)                                                 \
  _(js::jit::TypeOfEqObject)                                                   \
  _(js::jit::WrapObjectPure)                                                   \
  ABIFUNCTION_FUZZILLI_LIST(_)                                                 \
  _(js::MapIteratorObject::next)                                               \
  _(js::NativeObject::addDenseElementPure)                                     \
  _(js::NativeObject::growSlotsPure)                                           \
  _(js::NumberMod)                                                             \
  _(js::NumberToStringPure)                                                    \
  _(js::ObjectClassToString)                                                   \
  _(js::powi)                                                                  \
  _(js::ProxyGetProperty)                                                      \
  _(js::RoundFloat16)                                                          \
  _(js::SetIteratorObject::next)                                               \
  _(js::StringToNumberPure)                                                    \
  _(js::TypedArrayFillBigInt)                                                  \
  _(js::TypedArrayFillDouble)                                                  \
  _(js::TypedArrayFillFloat32)                                                 \
  _(js::TypedArrayFillInt32)                                                   \
  _(js::TypedArrayFillInt64)                                                   \
  _(js::TypedArraySetFromSubarrayInfallible)                                   \
  _(js::TypedArraySetInfallible)                                               \
  _(js::TypedArraySortFromJit)                                                 \
  _(js::TypeOfObject)                                                          \
  _(js::WeakMapObject::getObject)                                              \
  _(js::WeakMapObject::hasObject)                                              \
  _(js::WeakSetObject::hasObject)                                              \
  _(mozilla::SIMD::memchr16)                                                   \
  _(mozilla::SIMD::memchr2x16)                                                 \
  _(mozilla::SIMD::memchr2x8)                                                  \
  _(mozilla::SIMD::memchr8)

#define ABIFUNCTION_AND_SYMBOL_LIST(_)                                         \
  ABIFUNCTION_AND_SYMBOL_JS_GC_PROBES_LIST(_)                                  \
  ABIFUNCTION_AND_SYMBOL_JS_CODEGEN_ARM_LIST(_)                                \
  ABIFUNCTION_AND_SYMBOL_WASM_CODEGEN_DEBUG_LIST(_)                            \
  _(js::ArgumentsObject::finishForIonPure, finishForIonPure)                   \
  _(js::ArgumentsObject::finishInlineForIonPure, finishInlineForIonPure)       \
  _(js::ArrayShiftMoveElements, ArrayShiftMoveElements)                        \
  _(js::ArraySortData::sortArrayWithComparator, sortArrayWithComparator)       \
  _(js::ArraySortData::sortTypedArrayWithComparator,                           \
    sortTypedArrayWithComparator)                                              \
  _(js::ArraySortFromJit, ArraySortFromJit)                                    \
  _(js::ecmaAtan2, ecmaAtan2)                                                  \
  _(js::ecmaHypot, ecmaHypot)                                                  \
  _(js::ecmaPow, ecmaPow)                                                      \
  _(js::EmulatesUndefined, EmulatesUndefined)                                  \
  _(js::EmulatesUndefinedCheckFuse, EmulatesUndefinedCheckFuse)                \
  _(js::ExecuteRegExpAtomRaw, ExecuteRegExpAtomRaw)                            \
  _(js::hypot3, hypot3)                                                        \
  _(js::hypot4, hypot4)                                                        \
  _(js::Interpret, Interpret)                                                  \
  _(js::Int32ToStringPure, Int32ToStringPure)                                  \
  _(js::irregexp::CaseInsensitiveCompareNonUnicode,                            \
    CaseInsensitiveCompareNonUnicode)                                          \
  _(js::irregexp::CaseInsensitiveCompareUnicode,                               \
    CaseInsensitiveCompareUnicode)                                             \
  _(js::irregexp::GrowBacktrackStack, GrowBacktrackStack)                      \
  _(js::irregexp::IsCharacterInRangeArray, IsCharacterInRangeArray)            \
  _(js::jit::AllocateAndInitTypedArrayBuffer, AllocateAndInitTypedArrayBuffer) \
  _(js::jit::AllocateBigIntNoGC, AllocateBigIntNoGC)                           \
  _(js::jit::AllocateFatInlineString, AllocateFatInlineString)                 \
  _(js::jit::AllocateDependentString, AllocateDependentString)                 \
  _(js::jit::AssertMapObjectHash, AssertMapObjectHash)                         \
  _(js::jit::AssertPropertyLookup, AssertPropertyLookup)                       \
  _(js::jit::AssertSetObjectHash, AssertSetObjectHash)                         \
  _(js::jit::AssertValidBigIntPtr, AssertValidBigIntPtr)                       \
  _(js::jit::AssertValidObjectPtr, AssertValidObjectPtr)                       \
  _(js::jit::AssertValidStringPtr, AssertValidStringPtr)                       \
  _(js::jit::AssertValidSymbolPtr, AssertValidSymbolPtr)                       \
  _(js::jit::AssertValidValue, AssertValidValue)                               \
  _(js::jit::AssumeUnreachable, AssumeUnreachable)                             \
  _(js::jit::AtomicsStore64, AtomicsStore64)                                   \
  _(js::jit::AtomizeStringNoGC, AtomizeStringNoGC)                             \
  _(js::jit::Bailout, Bailout)                                                 \
  _(js::jit::BigIntNumberEqual<js::jit::EqualityKind::Equal>,                  \
    BigIntNumberEqual_Equal)                                                   \
  _(js::jit::BigIntNumberEqual<js::jit::EqualityKind::NotEqual>,               \
    BigIntNumberEqual_NotEqual)                                                \
  _(js::jit::BigIntNumberCompare<js::jit::ComparisonKind::LessThan>,           \
    BigIntNumberCompare_LT)                                                    \
  _(js::jit::NumberBigIntCompare<js::jit::ComparisonKind::LessThan>,           \
    NumberBigIntCompare_LT)                                                    \
  _(js::jit::NumberBigIntCompare<js::jit::ComparisonKind::GreaterThanOrEqual>, \
    NumberBigIntCompare_GTE)                                                   \
  _(js::jit::BigIntNumberCompare<js::jit::ComparisonKind::GreaterThanOrEqual>, \
    BigIntNumberCompare_GTE)                                                   \
  _(js::jit::DateFillLocalTimeSlots, DateFillLocalTimeSlots)                   \
  _(js::jit::EqualStringsHelperPure, EqualStringsHelperPure)                   \
  _(js::jit::FinishBailoutToBaseline, FinishBailoutToBaseline)                 \
  _(js::jit::Float16ToFloat32, Float16ToFloat32)                               \
  _(js::jit::Float32ToFloat16, Float32ToFloat16)                               \
  _(js::jit::FrameIsDebuggeeCheck, FrameIsDebuggeeCheck)                       \
  _(js::jit::GetContextSensitiveInterpreterStub,                               \
    GetContextSensitiveInterpreterStub)                                        \
  _(js::jit::GetIndexFromString, GetIndexFromString)                           \
  _(js::jit::GetInt32FromStringPure, GetInt32FromStringPure)                   \
  _(js::jit::GetNativeDataPropertyPure, GetNativeDataPropertyPure)             \
  _(js::jit::GetNativeDataPropertyPureWithCacheLookup,                         \
    GetNativeDataPropertyPureWithCacheLookup)                                  \
  _(js::jit::GetNativeDataPropertyByValuePure,                                 \
    GetNativeDataPropertyByValuePure)                                          \
  _(js::jit::GlobalHasLiveOnDebuggerStatement,                                 \
    GlobalHasLiveOnDebuggerStatement)                                          \
  _(js::jit::HandleCodeCoverageAtPC, HandleCodeCoverageAtPC)                   \
  _(js::jit::HandleCodeCoverageAtPrologue, HandleCodeCoverageAtPrologue)       \
  _(js::jit::HandleException, HandleException)                                 \
  _(js::jit::HasNativeDataPropertyPure<false>,                                 \
    HasNativeDataPropertyPure_false)                                           \
  _(js::jit::HasNativeDataPropertyPure<true>, HasNativeDataPropertyPure_true)  \
  _(js::jit::HasNativeElementPure, HasNativeElementPure)                       \
  _(js::jit::InitBaselineFrameForOsr, InitBaselineFrameForOsr)                 \
  _(js::jit::InvalidationBailout, InvalidationBailout)                         \
  _(js::jit::InvokeFromInterpreterStub, InvokeFromInterpreterStub)             \
  _(js::jit::LazyLinkTopActivation, LazyLinkTopActivation)                     \
  _(js::jit::LinearizeForCharAccessPure, LinearizeForCharAccessPure)           \
  _(js::jit::ObjectHasGetterSetterPure, ObjectHasGetterSetterPure)             \
  _(js::jit::ObjectIsCallable, ObjectIsCallable)                               \
  _(js::jit::ObjectIsConstructor, ObjectIsConstructor)                         \
  _(js::jit::PostGlobalWriteBarrier, PostGlobalWriteBarrier)                   \
  _(js::jit::PostWriteBarrier, PostWriteBarrier)                               \
  _(js::jit::PostWriteElementBarrier, PostWriteElementBarrier)                 \
  _(js::jit::PreserveWrapper, PreserveWrapper)                                 \
  _(js::jit::Printf0, Printf0)                                                 \
  _(js::jit::Printf1, Printf1)                                                 \
  _(js::jit::StringFromCharCodeNoGC, StringFromCharCodeNoGC)                   \
  _(js::jit::StringTrimEndIndex, StringTrimEndIndex)                           \
  _(js::jit::StringTrimStartIndex, StringTrimStartIndex)                       \
  _(js::jit::TypeOfNameObject, TypeOfNameObject)                               \
  _(js::jit::TypeOfEqObject, TypeOfEqObject)                                   \
  _(js::jit::WrapObjectPure, WrapObjectPure)                                   \
  ABIFUNCTION_FUZZILLI_LIST(_)                                                 \
  _(js::MapIteratorObject::next, next)                                         \
  _(js::NativeObject::addDenseElementPure, addDenseElementPure)                \
  _(js::NativeObject::growSlotsPure, growSlotsPure)                            \
  _(js::NumberMod, NumberMod)                                                  \
  _(js::NumberToStringPure, NumberToStringPure)                                \
  _(js::ObjectClassToString, ObjectClassToString)                              \
  _(js::powi, powi)                                                            \
  _(js::ProxyGetProperty, ProxyGetProperty)                                    \
  _(js::RoundFloat16, RoundFloat16)                                            \
  _(js::SetIteratorObject::next, next)                                         \
  _(js::StringToNumberPure, StringToNumberPure)                                \
  _(js::TypedArrayFillBigInt, TypedArrayFillBigInt)                            \
  _(js::TypedArrayFillDouble, TypedArrayFillDouble)                            \
  _(js::TypedArrayFillFloat32, TypedArrayFillFloat32)                          \
  _(js::TypedArrayFillInt32, TypedArrayFillInt32)                              \
  _(js::TypedArrayFillInt64, TypedArrayFillInt64)                              \
  _(js::TypedArraySetFromSubarrayInfallible,                                   \
    TypedArraySetFromSubarrayInfallible)                                       \
  _(js::TypedArraySetInfallible, TypedArraySetInfallible)                      \
  _(js::TypedArraySortFromJit, TypedArraySortFromJit)                          \
  _(js::TypeOfObject, TypeOfObject)                                            \
  _(js::WeakMapObject::getObject, getObject)                                   \
  _(js::WeakMapObject::hasObject, hasObject)                                   \
  _(js::WeakSetObject::hasObject, hasObject)                                   \
  _(mozilla::SIMD::memchr16, memchr16)                                         \
  _(mozilla::SIMD::memchr2x16, memchr2x16)                                     \
  _(mozilla::SIMD::memchr2x8, memchr2x8)                                       \
  _(mozilla::SIMD::memchr8, memchr8)

// List of all ABI functions to be used with callWithABI, which are
// overloaded. Each entry stores the fully qualified name of the C++ function,
// followed by the signature of the function to be called. When the function
// is not overloaded, you should prefer adding the function to
// ABIFUNCTION_LIST instead. This list must be sorted with the name of the C++
// function.
#define ABIFUNCTION_AND_TYPE_LIST(_)                    \
  _(JS::ToInt32, int32_t (*)(double))                   \
  _(js::jit::RoundFloat16ToFloat32, float (*)(int32_t)) \
  _(js::jit::RoundFloat16ToFloat32, float (*)(float))   \
  _(js::jit::RoundFloat16ToFloat32, float (*)(double))

#define ABIFUNCTION_AND_SYMBOL_AND_TYPE_LIST(_)                   \
  _(JS::ToInt32, ToInt32, int32_t (*)(double))                    \
  _(js::jit::RoundFloat16ToFloat32, RoundFloat16ToFloat32_int32,  \
    float (*)(int32_t))                                           \
  _(js::jit::RoundFloat16ToFloat32, RoundFloat16ToFloat32_float,  \
    float (*)(float))                                             \
  _(js::jit::RoundFloat16ToFloat32, RoundFloat16ToFloat32_double, \
    float (*)(double))

#define ABIFUNCTIONSIG_LIST(_)                      \
  _(AtomicsCompareExchangeFn)                       \
  _(AtomicsReadWriteModifyFn)                       \
  _(bool (*)(BigInt*, BigInt*))                     \
  _(bool (*)(BigInt*, double))                      \
  _(bool (*)(double, BigInt*))                      \
  _(float (*)(float))                               \
  _(JSJitGetterOp)                                  \
  _(JSJitMethodOp)                                  \
  _(JSJitSetterOp)                                  \
  _(JSNative)                                       \
  _(js::UnaryMathFunctionType)                      \
  _(void (*)(js::gc::StoreBuffer*, js::gc::Cell**)) \
  _(void (*)(JSRuntime * rt, JSObject * *objp))     \
  _(void (*)(JSRuntime * rt, JSString * *stringp))  \
  _(void (*)(JSRuntime * rt, Shape * *shapep))      \
  _(void (*)(JSRuntime * rt, wasm::AnyRef * refp))  \
  _(void (*)(JSRuntime * rt, Value * vp))

#define COMMA ,

// List of all ABI function signature which are using a computed function
// pointer instead of a statically known function pointer.
#define ABIFUNCTIONSIG_AND_SYMBOL_LIST(_)                                      \
  _(AtomicsCompareExchangeFn,                                                  \
    {                                                                          \
        {AtomicsCompareExchange(Scalar::Int8), "AtomicsCompareExchange_int8"}, \
        {AtomicsCompareExchange(Scalar::Uint8),                                \
         "AtomicsCompareExchange_uint8"},                                      \
        {AtomicsCompareExchange(Scalar::Int16),                                \
         "AtomicsCompareExchange_int16"},                                      \
        {AtomicsCompareExchange(Scalar::Uint16),                               \
         "AtomicsCompareExchange_uint16"},                                     \
        {AtomicsCompareExchange(Scalar::Int32),                                \
         "AtomicsCompareExchange_int32"},                                      \
        {AtomicsCompareExchange(Scalar::Uint32),                               \
         "AtomicsCompareExchange_uint32"},                                     \
    })                                                                         \
  _(AtomicsReadWriteModifyFn,                                                  \
    {                                                                          \
        {AtomicsExchange(Scalar::Int8), "AtomicsExchange_int8"},               \
        {AtomicsExchange(Scalar::Uint8), "AtomicsExchange_uint8"},             \
        {AtomicsExchange(Scalar::Int16), "AtomicsExchange_int16"},             \
        {AtomicsExchange(Scalar::Uint16), "AtomicsExchange_uint16"},           \
        {AtomicsExchange(Scalar::Int32), "AtomicsExchange_int32"},             \
        {AtomicsExchange(Scalar::Uint32), "AtomicsExchange_uint32"},           \
                                                                               \
        {AtomicsAdd(Scalar::Int8), "AtomicsAdd_int8"},                         \
        {AtomicsAdd(Scalar::Uint8), "AtomicsAdd_uint8"},                       \
        {AtomicsAdd(Scalar::Int16), "AtomicsAdd_int16"},                       \
        {AtomicsAdd(Scalar::Uint16), "AtomicsAdd_uint16"},                     \
        {AtomicsAdd(Scalar::Int32), "AtomicsAdd_int32"},                       \
        {AtomicsAdd(Scalar::Uint32), "AtomicsAdd_uint32"},                     \
                                                                               \
        {AtomicsSub(Scalar::Int8), "AtomicsSub_int8"},                         \
        {AtomicsSub(Scalar::Uint8), "AtomicsSub_uint8"},                       \
        {AtomicsSub(Scalar::Int16), "AtomicsSub_int16"},                       \
        {AtomicsSub(Scalar::Uint16), "AtomicsSub_uint16"},                     \
        {AtomicsSub(Scalar::Int32), "AtomicsSub_int32"},                       \
        {AtomicsSub(Scalar::Uint32), "AtomicsSub_uint32"},                     \
                                                                               \
        {AtomicsAnd(Scalar::Int8), "AtomicsAnd_int8"},                         \
        {AtomicsAnd(Scalar::Uint8), "AtomicsAnd_uint8"},                       \
        {AtomicsAnd(Scalar::Int16), "AtomicsAnd_int16"},                       \
        {AtomicsAnd(Scalar::Uint16), "AtomicsAnd_uint16"},                     \
        {AtomicsAnd(Scalar::Int32), "AtomicsAnd_int32"},                       \
        {AtomicsAnd(Scalar::Uint32), "AtomicsAnd_uint32"},                     \
                                                                               \
        {AtomicsOr(Scalar::Int8), "AtomicsOr_int8"},                           \
        {AtomicsOr(Scalar::Uint8), "AtomicsOr_uint8"},                         \
        {AtomicsOr(Scalar::Int16), "AtomicsOr_int16"},                         \
        {AtomicsOr(Scalar::Uint16), "AtomicsOr_uint16"},                       \
        {AtomicsOr(Scalar::Int32), "AtomicsOr_int32"},                         \
        {AtomicsOr(Scalar::Uint32), "AtomicsOr_uint32"},                       \
                                                                               \
        {AtomicsXor(Scalar::Int8), "AtomicsXor_int8"},                         \
        {AtomicsXor(Scalar::Uint8), "AtomicsXor_uint8"},                       \
        {AtomicsXor(Scalar::Int16), "AtomicsXor_int16"},                       \
        {AtomicsXor(Scalar::Uint16), "AtomicsXor_uint16"},                     \
        {AtomicsXor(Scalar::Int32), "AtomicsXor_int32"},                       \
        {AtomicsXor(Scalar::Uint32), "AtomicsXor_uint32"},                     \
    })                                                                         \
  _(bool (*)(BigInt * COMMA BigInt*), {})                                      \
  _(bool (*)(BigInt * COMMA double), {})                                       \
  _(bool (*)(double COMMA BigInt*), {})                                        \
  _(float (*)(float), {})                                                      \
  _(JSJitGetterOp, {})                                                         \
  _(JSJitMethodOp, {})                                                         \
  _(JSJitSetterOp, {})                                                         \
  _(JSNative, {})                                                              \
  _(js::UnaryMathFunctionType, {})                                             \
  _(void (*)(js::gc::StoreBuffer * COMMA js::gc::Cell**), {})                  \
  _(void (*)(JSRuntime * rt COMMA JSObject * *objp),                           \
    {{JitObjectPreWriteBarrier, "JitObjectPreWriteBarrier"}})                  \
  _(void (*)(JSRuntime * rt COMMA JSString * *stringp),                        \
    {{JitStringPreWriteBarrier, "JitStringPreWriteBarrier"}})                  \
  _(void (*)(JSRuntime * rt COMMA Shape * *shapep),                            \
    {{JitShapePreWriteBarrier, "JitShapePreWriteBarrier"}})                    \
  _(void (*)(JSRuntime * rt COMMA wasm::AnyRef * refp),                        \
    {{JitWasmAnyRefPreWriteBarrier, "JitWasmAnyRefPreWriteBarrier"}})          \
  _(void (*)(JSRuntime * rt COMMA Value * vp),                                 \
    {{JitValuePreWriteBarrier, "JitValuePreWriteBarrier"}})

// GCC warns when the signature does not have matching attributes (for example
// [[nodiscard]]). Squelch this warning to avoid a GCC-only footgun.
#if MOZ_IS_GCC
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wignored-attributes"
#endif

#ifdef JS_SPASM
#  define DEF_TEMPLATE(fp, sym)                   \
    template <>                                   \
    struct ABIFunctionData<decltype(&fp), fp> {   \
      static constexpr bool registered = true;    \
      static constexpr const char* symbol = #sym; \
    };
ABIFUNCTION_AND_SYMBOL_LIST(DEF_TEMPLATE)
#  undef DEF_TEMPLATE
#else
#  define DEF_TEMPLATE(fp)                      \
    template <>                                 \
    struct ABIFunctionData<decltype(&fp), fp> { \
      static constexpr bool registered = true;  \
    };
ABIFUNCTION_LIST(DEF_TEMPLATE)
#  undef DEF_TEMPLATE
#endif

#ifdef JS_SPASM
#  define DEF_TEMPLATE(fp, sym, ...)              \
    template <>                                   \
    struct ABIFunctionData<__VA_ARGS__, fp> {     \
      static constexpr bool registered = true;    \
      static constexpr const char* symbol = #sym; \
    };
ABIFUNCTION_AND_SYMBOL_AND_TYPE_LIST(DEF_TEMPLATE)
#  undef DEF_TEMPLATE
#else
#  define DEF_TEMPLATE(fp, ...)                \
    template <>                                \
    struct ABIFunctionData<__VA_ARGS__, fp> {  \
      static constexpr bool registered = true; \
    };
ABIFUNCTION_AND_TYPE_LIST(DEF_TEMPLATE)
#  undef DEF_TEMPLATE
#endif

// Define a known list of function signatures.
#ifdef JS_SPASM
#  define DEF_TEMPLATE(...)                                  \
    template <>                                              \
    struct ABIFunctionSignatureData<__VA_ARGS__> {           \
      static constexpr bool registered = true;               \
      static ABIFunctionSignatureMap<__VA_ARGS__> lookupSym; \
    };
ABIFUNCTIONSIG_LIST(DEF_TEMPLATE)
#  undef DEF_TEMPLATE
#else
#  define DEF_TEMPLATE(...)                        \
    template <>                                    \
    struct ABIFunctionSignatureData<__VA_ARGS__> { \
      static constexpr bool registered = true;     \
    };
ABIFUNCTIONSIG_LIST(DEF_TEMPLATE)
#  undef DEF_TEMPLATE
#endif

#if MOZ_IS_GCC
#  pragma GCC diagnostic pop
#endif

}  // namespace jit
}  // namespace js

// Make sure that all names are fully qualified (or at least, are resolvable
// within the toplevel namespace).
//
// Previously this was accomplished just by using `::fp` to force resolution
// within the toplevel namespace, but (1) that prevented using templated
// functions with more than one parameter (eg `void foo<T, U>`) because the
// macro split on the comma and wrapping it in parens doesn't work because
// `::(foo)` is invalid; and (2) that would only check the function name itself,
// not eg template parameters.
namespace check_fully_qualified {
#define CHECK_NS_VISIBILITY(fp)                               \
  [[maybe_unused]] static constexpr decltype(&fp) MOZ_CONCAT( \
      fp_, __COUNTER__) = nullptr;
ABIFUNCTION_LIST(CHECK_NS_VISIBILITY)
#undef CHECK_NS_VISIBILITY
}  // namespace check_fully_qualified

#endif  // jit_VMFunctionList_inl_h
