/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 * vim: set ts=8 sts=2 et sw=2 tw=80:
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "jit/AOT.h"

#include "mozilla/Maybe.h"
#include "mozilla/Sprintf.h"

#include <fstream>
#include <string>

#include "gc/Zone.h"
#include "jit/JitCode.h"
#include "jit/JitRuntime.h"
#include "jit/JitSpewer.h"
#include "jit/JitZone.h"
#include "vm/JSContext.h"

#include "vm/Realm-inl.h"

namespace js::jit {

JitCode* AllocateAOTCode(JSContext* cx,
                               const AOTBlobDirectoryEntry* entry,
                               uint8_t* textBase, CodeKind codeKind) {
  mozilla::Maybe<AutoAllocInAtomsZone> az;
  if (!cx->zone() || !cx->zone()->isAtomsZone()) {
    az.emplace(cx);
  }

  if (!cx->zone()->ensureJitZoneExists(cx)) {
    ReportOutOfMemory(cx);
    return nullptr;
  }

  uint8_t* codeStart = textBase + entry->codeOffset;
  JitCode* code = JitCode::NewStatic(cx, codeStart, entry->codeSize, codeKind);
  if (!code) {
    return nullptr;
  }

  return code;
}

mozilla::Maybe<AOTSlot> AOTIndirectionTable::findSlot(uintptr_t value) const {
  if (value == 0) return mozilla::Nothing();
  for (uint32_t i = 0; i < uint32_t(AOTSlot::Count); i++) {
    if (slots_[i] == value) {
      return mozilla::Some(AOTSlot(i));
    }
  }
  return mozilla::Nothing();
}

void AOTIndirectionTable::dump() const {
  for (uint32_t i = 0; i < uint32_t(AOTSlot::Count); i++) {
    JitSpew(JitSpew_BaselineAOT, "  slot[%u] %-30s = %p",
            i, AOTSlotName(AOTSlot(i)),
            (void*)get(AOTSlot(i)));
  }
}

AOTSlot AOTIndirectionTable::findSlotOrCrash(uintptr_t value) const {
  auto slot = findSlot(value);
  if (!slot) {
    JitSpew(JitSpew_BaselineAOT, "No AOT slot for %p", (void*)value);
    dump();
    MOZ_CRASH("No AOT slot for pointer");
  }
  return *slot;
}

AOTBlobWriter::AOTBlobWriter(AOTBlobKind kind, uint32_t nameHash,
                             uint32_t corpusIndex, std::string name)
    : kind_(kind),
      nameHash_(nameHash),
      corpusIndex_(corpusIndex),
      name_(std::move(name)) {}

static void emitAsmBytes(std::ostream& out, const uint8_t* data, size_t len) {
  for (size_t i = 0; i < len; i += 16) {
    size_t end = std::min(i + 16, len);
    out << "    .byte ";
    for (size_t j = i; j < end; j++) {
      char buf[8];
      SprintfLiteral(buf, "%s0x%02x", j > i ? ", " : "", unsigned(data[j]));
      out << buf;
    }
    out << "\n";
  }
}

static void emitAsmZeroPadding(std::ostream& out, size_t len) {
  if (len > 0) {
    out << "    .zero " << len << "\n";
  }
}

bool AOTContainerWriter::finalize(std::ostream& out) {
  uint32_t blobCount = blobs_.length();
  if (blobCount == 0) return true;

  Vector<AOTBlobDirectoryEntry, 2, SystemAllocPolicy> dirEntries;
  if (!dirEntries.reserve(blobCount)) return false;

  uint32_t textCursor = 0;
  for (uint32_t i = 0; i < blobCount; i++) {
    const auto& blob = blobs_[i];
    AOTBlobDirectoryEntry e{};
    e.kind = blob.kind();
    e.nameHash = blob.nameHash();
    e.corpusIndex = blob.corpusIndex();
    e.codeSize = blob.codeBytes().size();
    e.manifestSize = blob.manifestBytes().size();
    e.metadataSize = blob.metadataBytes().size();

    textCursor = js::AlignBytes(textCursor, kAOTAlignment);
    e.codeOffset = textCursor;
    textCursor += e.codeSize;

    dirEntries.infallibleAppend(e);
  }

  uint32_t dirSize =
      sizeof(AOTContainerHeader) + blobCount * sizeof(AOTBlobDirectoryEntry);
  uint32_t rodataDataStart = js::AlignBytes(dirSize, kAOTAlignment);

  uint32_t metaCursor = rodataDataStart;
  for (uint32_t i = 0; i < blobCount; i++) {
    dirEntries[i].manifestOffset = metaCursor;
    metaCursor += dirEntries[i].manifestSize;

    dirEntries[i].metadataOffset = metaCursor;
    metaCursor += dirEntries[i].metadataSize;

    metaCursor = js::AlignBytes(metaCursor, kAOTAlignment);
  }

  AOTContainerHeader hdr{};
  hdr.magic = AOT_CONTAINER_MAGIC;
  hdr.version = AOT_CONTAINER_VERSION;
  hdr.blobCount = blobCount;
  hdr.padding = 0;

  out << "// AOT Baseline - generated by --aot-dump-baseline\n";
  out << "// " << blobCount << " blob(s)\n";

  out << ".section .text.aot,\"ax\",@progbits\n";
  out << ".balign " << kAOTAlignment << "\n";
  out << ".global bl_aot_text_start\n";
  out << ".global bl_aot_text_end\n";
  out << "bl_aot_text_start:\n";

  for (uint32_t i = 0; i < blobCount; i++) {
    const auto& blob = blobs_[i];

    uint32_t padBefore = dirEntries[i].codeOffset -
        (i == 0 ? 0 : (dirEntries[i-1].codeOffset + dirEntries[i-1].codeSize));
    if (padBefore > 0) {
      emitAsmZeroPadding(out, padBefore);
    }

    out << "// --- Code blob " << i << " " << blob.name() << " ---\n";
    out << "bl_aot_" << blob.name() << "_code:\n";
    auto codeBytes = blob.codeBytes();
    if (!codeBytes.empty()) {
      emitAsmBytes(out, codeBytes.data(), codeBytes.size());
    }
  }

  out << "bl_aot_text_end:\n";

  out << ".section .rodata\n";
  out << ".balign " << kAOTAlignment << "\n";
  out << ".global bl_aot_container_start\n";
  out << ".global bl_aot_container_end\n";
  out << "bl_aot_container_start:\n";

  out << "// --- Container Header ---\n";
  emitAsmBytes(out, reinterpret_cast<const uint8_t*>(&hdr), sizeof(hdr));

  for (uint32_t i = 0; i < blobCount; i++) {
    out << "// --- Directory Entry " << i << " (kind="
        << static_cast<uint32_t>(dirEntries[i].kind) << ") ---\n";
    emitAsmBytes(out, reinterpret_cast<const uint8_t*>(&dirEntries[i]),
                 sizeof(AOTBlobDirectoryEntry));
  }

  size_t padSize = rodataDataStart - dirSize;
  if (padSize > 0) {
    out << "// --- Alignment padding ---\n";
    emitAsmZeroPadding(out, padSize);
  }

  for (uint32_t i = 0; i < blobCount; i++) {
    const auto& blob = blobs_[i];

    out << "// --- Manifest/Metadata " << i << " " << blob.name() << " ---\n";

    out << "bl_aot_" << blob.name() << "_manifest:\n";
    auto manifestBytes = blob.manifestBytes();
    if (!manifestBytes.empty()) {
      emitAsmBytes(out, manifestBytes.data(), manifestBytes.size());
    }

    out << "bl_aot_" << blob.name() << "_metadata:\n";
    auto metadataBytes = blob.metadataBytes();
    if (!metadataBytes.empty()) {
      emitAsmBytes(out, metadataBytes.data(), metadataBytes.size());
    }

    if (i + 1 < blobCount) {
      uint32_t curPos = dirEntries[i].metadataOffset + metadataBytes.size();
      uint32_t nextAligned = js::AlignBytes(curPos, kAOTAlignment);
      if (nextAligned > curPos) {
        out << "// --- Inter-blob padding ---\n";
        emitAsmZeroPadding(out, nextAligned - curPos);
      }
    }
  }

  out << "bl_aot_container_end:\n";
  out << ".section .note.GNU-stack,\"\",@progbits\n";
  return true;
}

/* static */
mozilla::Maybe<AOTContainerReader> AOTContainerReader::fromEmbedded() {
  if (GetAOTContainerSize() < sizeof(AOTContainerHeader)) {
    return mozilla::Nothing();
  }

  const auto* hdr = reinterpret_cast<const AOTContainerHeader*>(
      GetAOTContainer());
  if (hdr->magic != AOT_CONTAINER_MAGIC ||
      hdr->version != AOT_CONTAINER_VERSION) {
    return mozilla::Nothing();
  }

  const auto* dir = reinterpret_cast<const AOTBlobDirectoryEntry*>(
      GetAOTContainer() + sizeof(AOTContainerHeader));

  return mozilla::Some(AOTContainerReader(
      dir, GetAOTContainer(), GetAOTTextBase(), hdr->blobCount));
}

mozilla::Maybe<AOTBlobReader> AOTContainerReader::getBlob(
    AOTBlobKind kind, uint32_t nameHash) const {
  for (uint32_t i = 0; i < blobCount_; i++) {
    if (dir_[i].kind != kind) continue;
    if (nameHash != 0 && dir_[i].nameHash != nameHash) continue;
    // NOTE(aot): skip empty directory entries (holes from partial dumps).
    if (dir_[i].codeSize == 0 && dir_[i].manifestSize == 0 &&
        dir_[i].metadataSize == 0) {
      continue;
    }
    return mozilla::Some(AOTBlobReader(
        &dir_[i],
        textBase_ + dir_[i].codeOffset,
        containerBase_ + dir_[i].manifestOffset,
        containerBase_ + dir_[i].metadataOffset));
  }
  return mozilla::Nothing();
}

}  // namespace js::jit
