/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 * vim: set ts=8 sts=2 et sw=2 tw=80:
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef jit_BaselineInterpreterMetadata_h
#define jit_BaselineInterpreterMetadata_h

#include <fstream>
#include <string>

#include "jit/JitCode.h"
#include "vm/Opcodes.h"

namespace js {
namespace jit {

// Metadata about the Baseline Interpreter for AOT compilation.
// Encapsulates information needed to reconstruct baseline from
// an AOT-compiled blob.
class BaselineInterpreterMetadata {
 public:
  // Offsets to key entry points in the interpreter code.
  struct EntryPoints {
    uint32_t interpretOp = 0;
    uint32_t interpretOpNoDebugTrap = 0;
    uint32_t bailoutPrologue = 0;
    uint32_t profilerEnterToggle = 0;
    uint32_t profilerExitToggle = 0;
    uint32_t debugTrapHandler = 0;
  };

  // Offset information for opcode handlers.
  struct OpcodeHandler {
    uint32_t opcode;
    uint32_t offset;
  };

  // IC return offset information.
  struct ICReturnOffset {
    uint32_t offset;
    uint32_t opcode;  // JSOp as uint32_t for serialization
  };

  // CallVM offsets for debugger support.
  struct CallVMOffsets {
    uint32_t debugPrologue = 0;
    uint32_t debugEpilogue = 0;
    uint32_t debugAfterYield = 0;
  };

  BaselineInterpreterMetadata() = default;

  // Set the dispatch table offset.
  void setDispatchTableOffset(uint32_t offset) {
    dispatchTableOffset_ = offset;
  }

  // Set entry point offsets.
  void setEntryPoints(const EntryPoints& entryPoints) {
    entryPoints_ = entryPoints;
  }

  // Add an opcode handler offset.
  void addOpcodeHandler(uint32_t opcode, uint32_t offset) {
    opcodeHandlers_.push_back({opcode, offset});
  }

  // Add debug instrumentation offset.
  void addDebugInstrumentationOffset(uint32_t offset) {
    debugInstrumentationOffsets_.push_back(offset);
  }

  // Add debug trap offset.
  void addDebugTrapOffset(uint32_t offset) {
    debugTrapOffsets_.push_back(offset);
  }

  // Add code coverage offset.
  void addCodeCoverageOffset(uint32_t offset) {
    codeCoverageOffsets_.push_back(offset);
  }

  // Add IC return offset.
  void addICReturnOffset(uint32_t offset, uint32_t opcode) {
    icReturnOffsets_.push_back({offset, opcode});
  }

  // Add table label offset (for patching dispatch table references).
  void addTableLabelOffset(uint32_t offset) {
    tableLabelOffsets_.push_back(offset);
  }

  // Set CallVM offsets.
  void setCallVMOffsets(const CallVMOffsets& offsets) {
    callVMOffsets_ = offsets;
  }

  // Serialize metadata to YAML and write to a file.
  bool writeToFile(const char* filename) const {
    std::ofstream out(filename);
    if (!out) {
      return false;
    }

    out << "# Generated by BaselineInterpreterGenerator.cpp\n";
    out << "# Metadata about the baseline interpreter binary\n\n";

    out << "metadata:\n";
    out << "  dispatch_table_offset: " << dispatchTableOffset_ << "\n\n";

    out << "  entry_points:\n";
    out << "    interpret_op: " << entryPoints_.interpretOp << "\n";
    out << "    interpret_op_no_debug_trap: "
        << entryPoints_.interpretOpNoDebugTrap << "\n";
    out << "    bailout_prologue: " << entryPoints_.bailoutPrologue << "\n";
    out << "    profiler_enter_toggle: " << entryPoints_.profilerEnterToggle << "\n";
    out << "    profiler_exit_toggle: " << entryPoints_.profilerExitToggle << "\n";
    out << "    debug_trap_handler: " << entryPoints_.debugTrapHandler << "\n\n";

    out << "  opcode_offsets:\n";
    for (const auto& handler : opcodeHandlers_) {
      out << "    - { opcode: " << handler.opcode
          << ", offset: " << handler.offset << " }\n";
    }
    out << "\n";

    // Debug instrumentation offsets
    out << "  debug_instrumentation_offsets: [";
    for (size_t i = 0; i < debugInstrumentationOffsets_.size(); i++) {
      if (i > 0) out << ", ";
      out << debugInstrumentationOffsets_[i];
    }
    out << "]\n\n";

    // Debug trap offsets
    out << "  debug_trap_offsets: [";
    for (size_t i = 0; i < debugTrapOffsets_.size(); i++) {
      if (i > 0) out << ", ";
      out << debugTrapOffsets_[i];
    }
    out << "]\n\n";

    // Code coverage offsets
    out << "  code_coverage_offsets: [";
    for (size_t i = 0; i < codeCoverageOffsets_.size(); i++) {
      if (i > 0) out << ", ";
      out << codeCoverageOffsets_[i];
    }
    out << "]\n\n";

    // Table label offsets (for dispatch table patching)
    out << "  table_label_offsets: [";
    for (size_t i = 0; i < tableLabelOffsets_.size(); i++) {
      if (i > 0) out << ", ";
      out << tableLabelOffsets_[i];
    }
    out << "]\n\n";

    // IC return offsets
    out << "  ic_return_offsets:\n";
    for (const auto& ic : icReturnOffsets_) {
      out << "    - { offset: " << ic.offset
          << ", opcode: " << ic.opcode << " }\n";
    }
    out << "\n";

    // CallVM offsets
    out << "  callvm_offsets:\n";
    out << "    debug_prologue: " << callVMOffsets_.debugPrologue << "\n";
    out << "    debug_epilogue: " << callVMOffsets_.debugEpilogue << "\n";
    out << "    debug_after_yield: " << callVMOffsets_.debugAfterYield << "\n";

    out << "\n# Patches needed for runtime relocation\n";
    out << "# Add your patches here manually or from analysis\n";
    out << "patches: []\n";

    out.close();
    return true;
  }

  // Getters for reading metadata (used by AOT loading code).
  uint32_t dispatchTableOffset() const { return dispatchTableOffset_; }
  const EntryPoints& entryPoints() const { return entryPoints_; }
  const auto& opcodeHandlers() const { return opcodeHandlers_; }
  const auto& debugInstrumentationOffsets() const { return debugInstrumentationOffsets_; }
  const auto& debugTrapOffsets() const { return debugTrapOffsets_; }
  const auto& codeCoverageOffsets() const { return codeCoverageOffsets_; }
  const auto& tableLabelOffsets() const { return tableLabelOffsets_; }
  const auto& icReturnOffsets() const { return icReturnOffsets_; }
  const CallVMOffsets& callVMOffsets() const { return callVMOffsets_; }

 private:
  uint32_t dispatchTableOffset_ = 0;
  EntryPoints entryPoints_;
  std::vector<OpcodeHandler> opcodeHandlers_;
  std::vector<uint32_t> debugInstrumentationOffsets_;
  std::vector<uint32_t> debugTrapOffsets_;
  std::vector<uint32_t> codeCoverageOffsets_;
  std::vector<uint32_t> tableLabelOffsets_;
  std::vector<ICReturnOffset> icReturnOffsets_;
  CallVMOffsets callVMOffsets_;
};

}  // namespace jit
}  // namespace js

#endif  // jit_BaselineInterpreterMetadata_h
