/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 * vim: set ts=8 sts=2 et sw=2 tw=80:
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "jit/BaselineAOT.h"

#include <cstdint>
#include <fstream>
#include <iomanip>
#include <string>

#include "frontend/CompilationStencil.h"
#include "gc/Zone.h"
#include "jit/AOT.h"
#include "jit/AOTInstrumentation.h"
#include "jit/BaselineJIT.h"
#include "jit/CacheIRCompiler.h"
#include "jit/IonTypes.h"
#include "jit/JitCode.h"
#include "jit/JitcodeMap.h"
#include "jit/JitContext.h"
#include "jit/JitOptions.h"
#include "jit/JitRuntime.h"
#include "jit/JitSpewer.h"
#include "jit/JitZone.h"
#include "jit/ProcessExecutableMemory.h"
#include "jit/VMFunctions.h"
#include "vm/JSAtomUtils.h"
#include "vm/JSContext.h"
#include "vm/JSFunction.h"
#include "vm/JSScript.h"
#include "vm/Runtime.h"

#include "jit/JitScript-inl.h"
#include "vm/GeckoProfiler-inl.h"
#include "vm/JSObject-inl.h"
#include "vm/JSScript-inl.h"

namespace js::jit {

// ---------------------------------------------------------------------------
// AOT container serialization (dump mode)
// ---------------------------------------------------------------------------

#ifdef ENABLE_AOT_BASELINE

static void emitAsmBytes(std::ostream& out, const uint8_t* data, size_t len) {
  for (size_t i = 0; i < len; i += 16) {
    size_t end = std::min(i + 16, len);
    out << "    .byte ";
    for (size_t j = i; j < end; j++) {
      if (j > i) out << ", ";
      out << "0x" << std::hex << std::setfill('0') << std::setw(2)
          << (unsigned)data[j];
    }
    out << std::dec << "\n";
  }
}

static void emitAsmZeroPadding(std::ostream& out, size_t len) {
  if (len > 0) {
    out << "    .zero " << len << "\n";
  }
}


// AOTBlobData is defined in BaselineAOT.h

// Write the multi-blob AOT container .S file.
// Code blobs go into .text.aot (executable), manifests/metadata into .rodata.
// codeOffset in directory entries is relative to bl_aot_text_start.
static bool writeAOTContainer(std::ostream& out,
                              const AOTBlobData* const* blobs,
                              uint32_t blobCount) {
  Vector<AOTBlobDirectoryEntry, 2, SystemAllocPolicy> dirEntries;
  if (!dirEntries.reserve(blobCount)) {
    return false;
  }

  // First pass: compute code offsets relative to text section start,
  // and metadata offsets relative to rodata metadata area start.
  uint32_t textCursor = 0;
  uint32_t metaCursor = 0;
  for (uint32_t i = 0; i < blobCount; i++) {
    AOTBlobDirectoryEntry e = blobs[i]->dirEntry;

    // Code offset is relative to bl_aot_text_start.
    textCursor = js::AlignBytes(textCursor, 16u);
    e.codeOffset = textCursor;
    e.codeSize = blobs[i]->code.length();
    textCursor += e.codeSize;

    // Manifest/metadata offsets are relative to bl_aot_container_start.
    // We'll compute these after we know the rodata layout.
    e.manifestSize = blobs[i]->manifest.length();
    e.metadataSize = blobs[i]->metadata.length();

    // Temporarily store manifest/metadata sizes; offsets filled below.
    e.manifestOffset = 0;
    e.metadataOffset = 0;

    dirEntries.infallibleAppend(e);
  }

  // Rodata layout: header + directory + padding + manifest/metadata blobs.
  uint32_t dirSize =
      sizeof(AOTContainerHeader) + blobCount * sizeof(AOTBlobDirectoryEntry);
  uint32_t rodataDataStart = js::AlignBytes(dirSize, 16u);

  metaCursor = rodataDataStart;
  for (uint32_t i = 0; i < blobCount; i++) {
    dirEntries[i].manifestOffset = metaCursor;
    metaCursor += dirEntries[i].manifestSize;

    dirEntries[i].metadataOffset = metaCursor;
    metaCursor += dirEntries[i].metadataSize;

    metaCursor = js::AlignBytes(metaCursor, 16u);
  }

  AOTContainerHeader hdr;
  hdr.magic = AOT_CONTAINER_MAGIC;
  hdr.version = 0;
  hdr.blobCount = blobCount;
  hdr.padding = 0;

  out << "// AOT Baseline - generated by --dump-bl\n";
  out << "// " << blobCount << " blob(s)\n";

  // --- Executable code section ---
  out << ".section .text.aot,\"ax\",@progbits\n";
  out << ".balign 16\n";
  out << ".global bl_aot_text_start\n";
  out << ".global bl_aot_text_end\n";
  out << "bl_aot_text_start:\n";

  for (uint32_t i = 0; i < blobCount; i++) {
    const auto& blob = *blobs[i];
    const std::string& label = blob.name;

    uint32_t padBefore = dirEntries[i].codeOffset -
        (i == 0 ? 0 : (dirEntries[i-1].codeOffset + dirEntries[i-1].codeSize));
    if (padBefore > 0) {
      emitAsmZeroPadding(out, padBefore);
    }

    out << "// --- Code blob " << i << " " << label << " ---\n";
    out << "bl_aot_" << label << "_code:\n";
    if (blob.code.length() > 0) {
      emitAsmBytes(out, blob.code.begin(), blob.code.length());
    }
  }

  out << "bl_aot_text_end:\n";

  // --- Read-only data section (header, directory, manifests, metadata) ---
  out << ".section .rodata\n";
  out << ".balign 16\n";
  out << ".global bl_aot_container_start\n";
  out << ".global bl_aot_container_end\n";
  out << "bl_aot_container_start:\n";

  out << "// --- Container Header ---\n";
  emitAsmBytes(out, reinterpret_cast<const uint8_t*>(&hdr), sizeof(hdr));

  for (uint32_t i = 0; i < blobCount; i++) {
    out << "// --- Directory Entry " << i << " (kind="
        << static_cast<uint32_t>(dirEntries[i].kind) << ") ---\n";
    emitAsmBytes(out, reinterpret_cast<const uint8_t*>(&dirEntries[i]),
                 sizeof(AOTBlobDirectoryEntry));
  }

  size_t padSize = rodataDataStart - dirSize;
  if (padSize > 0) {
    out << "// --- Alignment padding ---\n";
    emitAsmZeroPadding(out, padSize);
  }

  for (uint32_t i = 0; i < blobCount; i++) {
    const auto& blob = *blobs[i];
    const std::string& label = blob.name;

    out << "// --- Manifest/Metadata " << i << " " << label << " ---\n";

    out << "bl_aot_" << label << "_manifest:\n";
    if (blob.manifest.length() > 0) {
      emitAsmBytes(out, blob.manifest.begin(), blob.manifest.length());
    }

    out << "bl_aot_" << label << "_metadata:\n";
    if (blob.metadata.length() > 0) {
      emitAsmBytes(out, blob.metadata.begin(), blob.metadata.length());
    }

    if (i + 1 < blobCount) {
      uint32_t curPos = dirEntries[i].metadataOffset + blob.metadata.length();
      uint32_t nextAligned = js::AlignBytes(curPos, 16u);
      if (nextAligned > curPos) {
        out << "// --- Inter-blob padding ---\n";
        emitAsmZeroPadding(out, nextAligned - curPos);
      }
    }
  }

  out << "bl_aot_container_end:\n";
  out << ".section .note.GNU-stack,\"\",@progbits\n";
  return true;
}

// Saved interpreter blob from BuildAndSaveInterpBlob(), reused by
// DumpAOTContainer() which runs later once a realm exists.
static mozilla::Maybe<AOTBlobData> sSavedInterpreterBlob;

bool BuildAndSaveInterpBlob(JitCode* code, const AOTInterpManifest& scalars,
                            const uint8_t* metadataBytes,
                            size_t metadataSize) {
  uint8_t* codeStart = code->raw();
  size_t codeSize = code->rawEnd() - codeStart;

  sSavedInterpreterBlob.reset();
  sSavedInterpreterBlob.emplace();
  AOTBlobData& interpBlob = *sSavedInterpreterBlob;

  interpBlob.dirEntry.kind = AOTBlobKind::BaselineInterpreter;
  interpBlob.dirEntry.nameHash = 0;
  interpBlob.name = "BaselineInterpreter";

  if (!AOTBlobData::appendBytes(interpBlob.code, codeStart, codeSize)) {
    return false;
  }

  if (!AOTBlobData::appendBytes(interpBlob.manifest, &scalars, 1)) {
    return false;
  }

  if (metadataSize > 0) {
    if (!interpBlob.metadata.append(metadataBytes, metadataSize)) {
      return false;
    }
  }

  JitSpew(JitSpew_BaselineAOT,
          "Saved interpreter blob: code=%zu manifest=%zu metadata=%zu",
          interpBlob.code.length(), interpBlob.manifest.length(),
          interpBlob.metadata.length());

  return true;
}

// ---------------------------------------------------------------------------
// Self-hosted function AOT compilation
// ---------------------------------------------------------------------------

static bool compileAOTSelfHosted(JSContext* cx, Handle<JSAtom*> atom,
                                 AOTBlobData* blobOut) {
  Rooted<PropertyName*> name(cx, atom->asPropertyName());
  auto indexRange = cx->runtime()->getSelfHostedScriptIndexRange(name);
  if (!indexRange) {
    return false;
  }
  AutoSuppressAllocationMetadataBuilder suppressMetadata(cx);

  UniqueChars nameStr = AtomToPrintableString(cx, atom);
  if (!nameStr) {
    return false;
  }

  RootedFunction fun(
      cx, cx->runtime()->selfHostStencil().instantiateSelfHostedLazyFunction(
              cx, cx->runtime()->selfHostStencilInput().atomCache,
              indexRange->start, name));
  if (!fun) {
    return false;
  }
  if (!cx->runtime()->delazifySelfHostedFunction(cx, name, fun)) {
    return false;
  }

  Rooted<JSScript*> script(cx, fun->nonLazyScript());
  MOZ_ASSERT(script);

  if (!CanBaselineInterpretScript(script)) {
    return false;
  }

  if (!cx->zone()->ensureJitZoneExists(cx)) {
    return false;
  }
  AutoKeepJitScripts keepJitScript(cx);
  if (!script->ensureHasJitScript(cx, keepJitScript)) {
    return false;
  }

  AOTContext aotCtx(&cx->runtime()->jitRuntime()->aotIndirectionTable());

  BaselineOptions options({BaselineOption::ForceMainThreadCompilation});
  MethodStatus result = BaselineCompile(cx, script, options, &aotCtx);
  if (result != Method_Compiled) {
    return false;
  }
  MOZ_ASSERT(script->hasBaselineScript());

  BaselineScript* bs = script->baselineScript();
  JitCode* jitCode = bs->method();

  AOTScriptManifest sm{};
  bs->fillAOTManifest(&sm, &blobOut->metadata);
  sm.codeSize = jitCode->instructionsSize();
  sm.headerSize = jitCode->headerSize();
  blobOut->dirEntry.kind = AOTBlobKind::SelfHostedFunction;
  blobOut->dirEntry.nameHash = mozilla::HashString(nameStr.get());
  blobOut->name = nameStr.get();

  if (!AOTBlobData::appendBytes(blobOut->code, jitCode->raw(),
                                jitCode->instructionsSize())) {
    return false;
  }
  if (!AOTBlobData::appendBytes(blobOut->manifest, &sm, 1)) {
    return false;
  }

  JitSpew(JitSpew_BaselineAOT,
          "AOT Compiled '%-22s' size=%5ub  callSites=%3u  osr=%u",
          nameStr.get(), sm.codeSize, sm.retAddrEntryCount,
          sm.osrEntryCount);

  return true;
}

bool DumpAOTContainer(JSContext* cx, ICProfileMap* pgoProfiles) {
  MOZ_ASSERT(JitOptions.dumpBaselineInterp ||
             JitOptions.dumpBaselineSelfHosted ||
             JitOptions.dumpAOTICs);

  const char* outPath = kAOTOutputPath;
  Vector<AOTBlobData, 0, SystemAllocPolicy> funcBlobs;
  Vector<const AOTBlobData*, 0, SystemAllocPolicy> blobPtrs;

  if (sSavedInterpreterBlob) {
    if (!blobPtrs.append(&*sSavedInterpreterBlob)) {
      return false;
    }
  }

  if (JitOptions.dumpBaselineSelfHosted) {
    // Self-hosted compilation needs a realm (instantiateSelfHostedLazyFunction
    // accesses cx->global()). Skip if no realm is available -- the caller must
    // ensure a realm exists (the shell does this naturally via JSAutoRealm).
    if (!cx->realm()) {
      JitSpew(JitSpew_BaselineAOT,
              "Skipping self-hosted dump: no realm available");
    } else {

    static const char* const kSelfHostedAllowlist[] = {
        "ArrayMap", "ArrayFilter", "ArrayReduce", "ArrayReduceRight",
        "ArrayForEach", "ArrayFind", "ArrayFindIndex", "ArraySome",
        "ArrayEvery", "ArrayIncludes", "ArrayFrom", "ArrayFlat",
        "ArrayFlatMap", "ArraySort", "ArrayOf", "ArraySlice",
        "ArrayKeys", "ArrayValues", "ArrayEntries", "StringReplace",
        "StringSplit", "StringStartsWith", "StringEndsWith", "StringIncludes",
        "StringTrim", "StringPadStart", "StringPadEnd", "ObjectKeys",
        "ObjectValues", "ObjectEntries", "ObjectAssign", "PromiseThen",
        "NumberToLocaleString", "DateToLocaleString", "RegExpPrototypeExec",
        "TypedArraySort",
    };

    uint32_t compiled = 0;
    uint32_t skipped = 0;
    auto& map = cx->runtime()->selfHostScriptMap.ref();
    for (const char* name : kSelfHostedAllowlist) {
      Rooted<JSAtom*> atom(cx, Atomize(cx, name, strlen(name)));
      if (!atom) {
        skipped++;
        continue;
      }
      auto ptr = map.readonlyThreadsafeLookup(atom->asPropertyName());
      if (!ptr) {
        skipped++;
        continue;
      }

      AOTBlobData blob;
      if (!compileAOTSelfHosted(cx, atom, &blob)) {
        skipped++;
        continue;
      }
      compiled++;
      if (!funcBlobs.append(std::move(blob))) {
        return false;
      }
    }
    JitSpew(JitSpew_BaselineAOT,
            "Self-hosted AOT: compiled %u, skipped %u", compiled, skipped);
    for (const auto& blob : funcBlobs) {
      if (!blobPtrs.append(&blob)) {
        return false;
      }
    }
    } // if (cx->realm())
  }

  auto icBlobs = GetSavedICBlobs();
  for (const auto& icBlob : icBlobs) {
    if (!blobPtrs.append(&icBlob)) {
      return false;
    }
  }

  if (blobPtrs.empty()) {
    JitSpew(JitSpew_BaselineAOT, "No blobs to write, skipping container.");
    return true;
  }

  std::ofstream out(outPath, std::ios::trunc);
  if (!out.is_open()) {
    JitSpew(JitSpew_BaselineAOT, "Failed to open %s for writing.", outPath);
    return false;
  }

  uint32_t blobCount = static_cast<uint32_t>(blobPtrs.length());
  if (!writeAOTContainer(out, blobPtrs.begin(), blobCount)) {
    return false;
  }

  out.close();

  JitSpew(JitSpew_BaselineAOT, "Wrote AOT container with %u blob(s) to %s",
          blobCount, outPath);
  JitSpew(JitSpew_BaselineAOT, "Rebuild the engine to use AOT mode.");

  sSavedInterpreterBlob.reset();
  ClearSavedICBlobs();

  return true;
}

// ---------------------------------------------------------------------------
// AOT interpreter loading (runtime)
// ---------------------------------------------------------------------------

bool LoadAOTInterpFromContainer(JSContext* cx,
                                BaselineInterpreter& interpreter) {
  AOT_TIMER_BEGIN(interp);

  const AOTBlobDirectoryEntry* entry =
      FindAOTBlob(AOTBlobKind::BaselineInterpreter);
  if (!entry) {
    JitSpew(JitSpew_BaselineAOT,
            "ERROR: No BaselineInterpreter blob in AOT container!");
    return false;
  }

  const uint8_t* containerBase = GetAOTContainer();

  if (entry->manifestSize != sizeof(AOTInterpManifest)) {
    JitSpew(JitSpew_BaselineAOT,
            "ERROR: Interpreter manifest size mismatch (expected %zu, got %u). "
            "Stale AOT container?",
            sizeof(AOTInterpManifest), entry->manifestSize);
    return false;
  }

  // Ensure debug trap handlers exist before allocating writable code.
  if (!cx->runtime()->jitRuntime()->ensureDebugTrapHandler(
          cx, DebugTrapHandlerKind::Interpreter)) {
    return false;
  }
  if (!cx->runtime()->jitRuntime()->ensureDebugTrapHandler(
          cx, DebugTrapHandlerKind::Compiler)) {
    return false;
  }

  // Populate debug trap handler slots now that they've been generated.
  AOTIndirectionTable& table = cx->runtime()->jitRuntime()->aotIndirectionTable();
  table.set(AOTSlot::DebugTrapInterpreter,
            uintptr_t(cx->runtime()->jitRuntime()->debugTrapHandler(
                DebugTrapHandlerKind::Interpreter)->raw()));
  table.set(AOTSlot::DebugTrapCompiler,
            uintptr_t(cx->runtime()->jitRuntime()->debugTrapHandler(
                DebugTrapHandlerKind::Compiler)->raw()));

  JitCode* code = AllocateAOTCode(
      cx, entry, GetAOTTextBase(), CodeKind::Other);
  if (!code) {
    return false;
  }

  if (!interpreter.initFromAOT(cx, code, entry, containerBase)) {
    JitSpew(JitSpew_BaselineAOT,
            "ERROR: Failed to initialize from AOT symbols");
    return false;
  }

  {
    auto profEntry = MakeJitcodeGlobalEntry<BaselineInterpreterEntry>(
        cx, code, code->raw(), code->rawEnd());
    if (!profEntry) {
      return false;
    }

    JitcodeGlobalTable* globalTable =
        cx->runtime()->jitRuntime()->getJitcodeGlobalTable();
    if (!globalTable->addEntry(std::move(profEntry))) {
      ReportOutOfMemory(cx);
      return false;
    }

    code->setHasBytecodeMap();
  }

  if (cx->runtime()->geckoProfiler().enabled()) {
    interpreter.toggleProfilerInstrumentation(true);
  }

  if (coverage::IsLCovEnabled()) {
    interpreter.toggleCodeCoverageInstrumentationUnchecked(true);
  }

  AOT_TIMER_END(interp, "aot-load", "interp", " bytes=%u", entry->codeSize);

  AOT_INSTR(AOTInstr_Lifecycle,
            "jit-compile tier=blinterp bytes=%u aot=1\n",
            entry->codeSize);

  return true;
}

// ---------------------------------------------------------------------------
// Self-hosted function loading (runtime)
// ---------------------------------------------------------------------------

bool LoadAOTSelfHosted(JSContext* cx, HandleScript script,
                       Handle<JSAtom*> name) {
  AOT_TIMER_BEGIN(sh);

  JS::AutoCheckCannotGC nogc;
  uint32_t nameHash = name->hasLatin1Chars()
      ? mozilla::HashStringKnownLength(name->latin1Chars(nogc), name->length())
      : mozilla::HashStringKnownLength(name->twoByteChars(nogc), name->length());

  const AOTBlobDirectoryEntry* entry =
      FindAOTBlob(AOTBlobKind::SelfHostedFunction, nameHash);
  if (!entry) {
    return false;
  }
  const uint8_t* containerBase = GetAOTContainer();

  JitSpew(JitSpew_BaselineAOT,
          "Loading AOT self-hosted function (nameHash=%u, codeSize=%u)",
          nameHash, entry->codeSize);

  if (entry->manifestSize != sizeof(AOTScriptManifest)) {
    JitSpew(JitSpew_BaselineAOT,
            "ERROR: Script manifest size mismatch (expected %zu, got %u). "
            "Stale AOT container?",
            sizeof(AOTScriptManifest), entry->manifestSize);
    return false;
  }

  AOTScriptManifest manifest;
  memcpy(&manifest, containerBase + entry->manifestOffset, sizeof(manifest));

  JitCode* code = AllocateAOTCode(
      cx, entry, GetAOTTextBase(), CodeKind::Baseline);
  if (!code) {
    return false;
  }

  BaselineScript* bs = BaselineScript::New(
      cx, manifest.warmUpCheckPrologueOffset,
      manifest.profilerEnterToggleOffset,
      manifest.profilerExitToggleOffset,
      manifest.retAddrEntryCount, manifest.osrEntryCount,
      manifest.debugTrapEntryCount, manifest.resumeEntryCount);
  if (!bs) {
    return false;
  }
  bs->setMethod(code);

  const uint8_t* meta = containerBase + entry->metadataOffset;
  auto retAddrs   = ReadMetadataArray<RetAddrEntry>(meta, manifest.retAddrEntryCount);
  auto osrEntries = ReadMetadataArray<BaselineScript::OSREntry>(meta, manifest.osrEntryCount);
  auto debugTraps = ReadMetadataArray<BaselineScript::DebugTrapEntry>(meta, manifest.debugTrapEntryCount);

  if (!retAddrs.empty())   bs->copyRetAddrEntries(retAddrs.data());
  if (!osrEntries.empty()) bs->copyOSREntries(osrEntries.data());
  if (!debugTraps.empty()) bs->copyDebugTrapEntries(debugTraps.data());

  bs->computeResumeNativeOffsets(script, ResumeOffsetEntryVector());

  // Generate a preamble trampoline that sets AOTSelfHostedPassReg (r11,
  // volatile) and jumps to the self-hosted code. Must be registered BEFORE
  // setBaselineScript, which triggers updateJitCodeRaw -> lookupAOTPreamble.
  // A JitContext is needed for MacroAssembler; one may not exist if we're
  // called lazily from delazifySelfHostedFunction rather than at init time.
  mozilla::Maybe<JitContext> jctx;
  if (!MaybeGetJitContext()) {
    jctx.emplace(cx);
  }
  JitRuntime* jrt = cx->runtime()->jitRuntime();
  JitCode* preamble = jrt->generateAOTPreamble(cx, code->raw(),
                                                AOTSelfHostedPassReg);
  if (!preamble) {
    return false;
  }
  JitRuntime::AOTPreambleEntry pe = { code->raw(), preamble };
  if (!jrt->aotPreambles_.append(pe)) {
    ReportOutOfMemory(cx);
    return false;
  }

  // Attach to script before fallible profiler registration so bs is not leaked.
  script->jitScript()->setBaselineScript(script, bs);

  {
    // Static AOT code shares .text addresses across realms. Only register
    // the jitcode map entry once per unique address range.
    JitcodeGlobalTable* globalTable =
        cx->runtime()->jitRuntime()->getJitcodeGlobalTable();
    if (!globalTable->lookup(code->raw())) {
      UniqueChars str =
          GeckoProfilerRuntime::allocProfileString(cx, script);
      if (!str) {
        return false;
      }

      auto profEntry = MakeJitcodeGlobalEntry<RealmIndependentSharedEntry>(
          cx, code, code->raw(), code->rawEnd(), std::move(str));
      if (!profEntry) {
        return false;
      }

      if (!globalTable->addEntry(std::move(profEntry))) {
        ReportOutOfMemory(cx);
        return false;
      }
      code->setHasBytecodeMap();
    }
  }

  if (cx->runtime()->jitRuntime()->isProfilerInstrumentationEnabled(
          cx->runtime())) {
    bs->toggleProfilerInstrumentation(true);
  }

  AOT_TIMER_END(sh, "aot-load", "selfhosted", " bytes=%u hash=%u",
                entry->codeSize, nameHash);

  return true;
}

// ---------------------------------------------------------------------------
// AOT IC stub loading (runtime)
// ---------------------------------------------------------------------------

bool LoadAOTICStubs(JSContext* cx) {
  MOZ_ASSERT(cx->inAtomsZone());
  AOT_TIMER_BEGIN(ics);

  JitZone* jitZone = cx->zone()->jitZone();
  if (!jitZone) {
    return false;
  }

  const uint8_t* containerBase = GetAOTContainer();
  uint8_t* textBase = GetAOTTextBase();
  uint32_t loadedCount = 0;
  uint32_t totalCount = 0;

  ForEachAOTBlob(AOTBlobKind::InlineCacheStub,
      [&](const AOTBlobDirectoryEntry* entry) {
    totalCount++;
    if (entry->manifestSize != sizeof(AOTICStubManifest)) {
      return;
    }

    AOTICStubManifest manifest;
    memcpy(&manifest, containerBase + entry->manifestOffset,
           sizeof(manifest));

    const uint8_t* meta = containerBase + entry->metadataOffset;
    auto cacheIRCode = ReadMetadataArray<uint8_t>(meta, manifest.cacheIRCodeLength);
    auto fieldTypes  = ReadMetadataArray<uint8_t>(meta, manifest.numStubFields);

    CacheIRStubInfo* stubInfo = CacheIRStubInfo::NewFromSerialized(
        manifest.kind, ICStubEngine::Baseline,
        manifest.makesGCCalls != 0,
        manifest.stubDataOffset,
        cacheIRCode.data(), cacheIRCode.size(),
        fieldTypes.data(), fieldTypes.size());
    if (!stubInfo) {
      return;
    }

    JitCode* code = AllocateAOTCode(
        cx, entry, textBase, CodeKind::Baseline);
    if (!code) {
      js_free(stubInfo);
      return;
    }

    code->setLocalTracingSlots(manifest.localTracingSlots);

    CacheIRStubKey::Lookup lookup(
        manifest.kind, ICStubEngine::Baseline,
        stubInfo->code(), stubInfo->codeLength());

    CacheIRStubInfo* existing = nullptr;
    if (jitZone->getBaselineCacheIRStubCode(lookup, &existing)) {
      js_free(stubInfo);
      return;
    }

    CacheIRStubKey key(stubInfo);
    if (!jitZone->putBaselineCacheIRStubCode(lookup, key, code)) {
      return;
    }

    AOT_INSTR(AOTInstr_IC, "ic-corpus kind=%s hash=%u code=%u idx=%u\n",
              CacheKindNames[uint8_t(manifest.kind)],
              unsigned(CacheIRStubKey::hash(lookup)),
              unsigned(code->instructionsSize()),
              totalCount - 1);

    loadedCount++;
  });

  if (loadedCount > 0) {
    JitSpew(JitSpew_BaselineAOT,
            "Loaded %u/%u AOT IC stubs from container",
            loadedCount, totalCount);
  }
  if (loadedCount < totalCount) {
    JitSpew(JitSpew_BaselineAOT,
            "WARNING: %u AOT IC stubs failed to load",
            totalCount - loadedCount);
  }

  AOT_TIMER_END(ics, "aot-load", "ics", " count=%u", loadedCount);

  return loadedCount > 0;
}

#endif  // ENABLE_AOT_BASELINE

}  // namespace js::jit
