# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Generates the C++ metadata structures and serialization helpers for each
# artifact kind declared by the image schema.

import io
import json
import struct

import yaml

HEADER_TEMPLATE = """\
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef %(includeguard)s
#define %(includeguard)s

/* Generated by jit/GenerateAOTImage.py from jit/AOTImageSchema.yaml. */

%(contents)s

#endif  // %(includeguard)s
"""


PRIMITIVES = {"u8": ("uint8_t", 1), "u16": ("uint16_t", 2), "u32": ("uint32_t", 4)}
COUNT_TYPE = ("uint32_t", 4)


def load_yaml(yaml_path):
    import buildconfig
    from mozbuild.preprocessor import Preprocessor

    pp = Preprocessor()
    pp.context.update(buildconfig.defines["ALLDEFINES"])
    pp.out = io.StringIO()
    pp.do_filter("substitution")
    pp.do_include(yaml_path)
    schema = yaml.safe_load(pp.out.getvalue())
    validate_schema(schema)
    return schema


def split_declaration(entry, context):
    if not isinstance(entry, dict) or len(entry) != 1:
        raise ValueError("%s must be a single 'type: member' pair" % context)
    return next(iter(entry.items()))


# The serialized member name is the last component of the metadata member path,
# so a nested member does not need to repeat itself in the schema.
def member_name(path):
    return path.rsplit(".", 1)[-1]


# Mirrors the compiler's aggregate layout by aligning each member naturally,
# with explicit padding members so that no byte of the serialized form is left
# indeterminate. A generated assertion detects layout differences.
def lay_out(fields):
    members = []
    offset = 0
    max_align = 1

    def pad(count):
        members.append({"name": "padding%d" % len(members), "padding": count})

    for f in fields:
        align = f["size"]
        max_align = max(max_align, align)
        if offset % align:
            pad(align - offset % align)
            offset += align - offset % align
        members.append(f)
        offset += f["size"]

    if offset % max_align:
        pad(max_align - offset % max_align)
        offset += max_align - offset % max_align

    return members, offset


def parse_blob(kind, artifact):
    metadata = artifact["metadata"]
    arrays = []
    for entry in metadata.get("arrays") or []:
        element, path = split_declaration(entry, "array in blob %s" % kind)
        arrays.append({"name": member_name(path), "path": path, "element": element})

    fields = []
    for entry in metadata.get("fields") or []:
        type_name, path = split_declaration(entry, "field in blob %s" % kind)
        if type_name not in PRIMITIVES:
            raise ValueError("unknown field type %s in blob %s" % (type_name, kind))
        cpp_type, size = PRIMITIVES[type_name]
        fields.append({
            "name": member_name(path),
            "path": path,
            "cpp_type": cpp_type,
            "size": size,
        })

    for a in arrays:
        cpp_type, size = COUNT_TYPE
        fields.append({
            "name": a["name"] + "Count",
            "path": a["path"] + ".length",
            "cpp_type": cpp_type,
            "size": size,
        })

    members, size = lay_out(fields)
    names = [m["name"] for m in members]
    if len(set(names)) != len(names):
        raise ValueError("duplicate serialized member name in blob %s" % kind)

    return {
        "kind": kind,
        "doc": artifact.get("doc"),
        "metadata_type": metadata["cpp_type"],
        "fields_type": "AOTFields_%s" % kind,
        "fields": fields,
        "arrays": arrays,
        "members": members,
        "size": size,
    }


def emit_lines(lines):
    return "\n".join(lines) + "\n"


def emit_doc(doc):
    if not doc:
        return []
    return ["// " + line if line else "//" for line in doc.splitlines()]


def emit_fields_pod(blob):
    name = blob["fields_type"]
    lines = ["struct %s {" % name]
    for m in blob["members"]:
        if "padding" in m:
            lines.append("  uint8_t %s[%d] = {};" % (m["name"], m["padding"]))
        else:
            lines.append("  %s %s = {};" % (m["cpp_type"], m["name"]))
    lines.append("};")
    lines.append("static_assert(sizeof(%s) == %d," % (name, blob["size"]))
    lines.append('              "%s size drift; edit AOTImageSchema.yaml");' % name)
    lines.append("static_assert(std::has_unique_object_representations_v<%s>," % name)
    lines.append('              "%s must serialize without implicit padding");' % name)
    return emit_lines(lines)


def metadata_expr(field):
    if field["path"].endswith(".length"):
        return "uint32_t(md.%s())" % field["path"]
    return "md.%s" % field["path"]


def emit_encode(blob):
    lines = [
        "[[nodiscard]] inline bool EncodeBlob_%s(" % blob["kind"],
        "    AOTBlobWriter& blob, const %s& md) {" % blob["metadata_type"],
        "  %s f = {};" % blob["fields_type"],
    ]
    for f in blob["fields"]:
        lines.append("  f.%s = %s;" % (f["name"], metadata_expr(f)))
    lines.append("  if (!blob.writeFields(f)) return false;")
    for a in blob["arrays"]:
        lines.append(
            "  if (!blob.writeArray<%s>(md.%s.begin(), md.%s.length())) "
            "return false;" % (a["element"], a["path"], a["path"])
        )
    lines.append("  return true;")
    lines.append("}")
    return emit_lines(lines)


def emit_decode(blob):
    lines = [
        "[[nodiscard]] inline bool DecodeBlob_%s(" % blob["kind"],
        "    AOTBlobReader& reader, %s* md) {" % blob["metadata_type"],
        "  if (reader.fieldsSize() != sizeof(%s)) return false;" % blob["fields_type"],
        "  %s f = reader.readFields<%s>();"
        % (blob["fields_type"], blob["fields_type"]),
    ]
    for f in blob["fields"]:
        if not f["path"].endswith(".length"):
            lines.append("  md->%s = f.%s;" % (f["path"], f["name"]))
    for a in blob["arrays"]:
        lines.append("  {")
        lines.append(
            "    auto src = reader.readArray<%s>(f.%sCount);"
            % (a["element"], a["name"])
        )
        lines.append(
            "    if (!md->%s.append(src.data(), src.size())) return false;" % a["path"]
        )
        lines.append("  }")
    lines.append("  return reader.arraysComplete();")
    lines.append("}")
    return emit_lines(lines)


def emit_blob(kind_id, blob):
    out = ["// ---- Blob: %s (kind %d) ----" % (blob["kind"], kind_id)]
    out.extend(emit_doc(blob["doc"]))
    out.append("")
    out.append(emit_fields_pod(blob))
    out.append(emit_encode(blob))
    out.append(emit_decode(blob))
    return "\n".join(out)


def main(c_out, yaml_path):
    schema = load_yaml(yaml_path)
    blobs = [
        parse_blob(kind, blob) for kind, blob in (schema.get("artifacts") or {}).items()
    ]

    body = [
        "#include <cstdint>",
        "#include <type_traits>",
        "",
        '#include "mozilla/Span.h"',
        "",
        '#include "jit/AOTImage.h"',
        '#include "jit/BaselineJIT.h"',
        "",
        "namespace js::jit {",
        "",
        emit_array_assertions(schema),
    ]
    for kind_id, blob in enumerate(blobs):
        body.append(emit_blob(kind_id, blob))
    body.append("}  // namespace js::jit")

    c_out.write(
        HEADER_TEMPLATE
        % {
            "includeguard": "jit_AOTImageGenerated_h",
            "contents": "\n".join(body),
        }
    )


WIRE_TYPES = {
    "u8": ("uint8_t", "B"),
    "u16": ("uint16_t", "H"),
    "u32": ("uint32_t", "I"),
    "bytes20": ("uint8_t", "20s"),
    "bytes32": ("uint8_t", "32s"),
}


def record_format(fields):
    return "<" + "".join(
        WIRE_TYPES[split_declaration(field, "record")[0]][1] for field in fields
    )


def key_fields(schema, artifact):
    fields = []
    for entry in schema["common_key_fields"] + artifact["compilation_key"]:
        declaration = dict(entry)
        metadata = declaration.pop("metadata", None)
        type_name, name = split_declaration(declaration, "compilation key field")
        field = {"type": type_name, "name": name}
        if metadata is not None:
            field["metadata"] = metadata
        fields.append(field)
    return fields


def validate_schema(schema):
    for kind, blob in schema["artifacts"].items():
        parsed = parse_blob(kind, blob)
        fields = key_fields(schema, blob)
        if len({field["name"] for field in fields}) != len(fields):
            raise ValueError(f"duplicate key field in {kind}")
        members = {field["name"] for field in parsed["fields"] + parsed["arrays"]}
        for field in fields:
            if field["type"] not in ("bool", "u32", "bytes", "u32_array"):
                raise ValueError(f"unknown key type in {kind}: {field['type']}")
            if "metadata" in field and field["metadata"] not in members:
                raise ValueError(f"unknown metadata member {field['metadata']}")
        widths = [parsed["size"], 4]
        for array in parsed["arrays"]:
            layout = schema["array_types"][array["element"]]
            if any(width % layout["alignment"] for width in widths):
                raise ValueError(f"array {array['name']} requires wire padding")
            widths.append(layout["size"])


def describe_schema(schema):
    description = {
        "constants": {k.upper(): v for k, v in schema["format"].items()},
        "records": {},
        "blobs": [],
    }
    for name, fields in schema["records"].items():
        description["records"][name] = {
            "format": record_format(fields),
            "names": [split_declaration(field, name)[1] for field in fields],
        }
    for kind, source in schema["artifacts"].items():
        blob = parse_blob(kind, source)
        fmt = "<"
        for member in blob["members"]:
            if "padding" in member:
                fmt += str(member["padding"]) + "x"
            else:
                fmt += {1: "B", 2: "H", 4: "I"}[member["size"]]
        arrays = [
            {"name": array["name"], **schema["array_types"][array["element"]]}
            for array in blob["arrays"]
        ]
        description["blobs"].append({
            "name": kind,
            "prefix": source["filename_prefix"],
            "format": fmt,
            "fields": [field["name"] for field in blob["fields"]],
            "arrays": arrays,
            "key": [
                {k: field[k] for k in ("name", "type", "metadata") if k in field}
                for field in key_fields(schema, source)
            ],
        })
    return description


def generate_descriptor(output, yaml_path):
    json.dump(describe_schema(load_yaml(yaml_path)), output, indent=2)
    output.write("\n")


def emit_array_assertions(schema):
    lines = []
    for name, layout in schema["array_types"].items():
        lines += [
            f"static_assert(sizeof({name}) == {layout['size']});",
            f"static_assert(alignof({name}) == {layout['alignment']});",
            f"static_assert(std::is_trivially_copyable_v<{name}>);",
            f"static_assert(std::has_unique_object_representations_v<{name}>);",
        ]
    return emit_lines(lines)


def generate_format_header(output, yaml_path):
    schema = load_yaml(yaml_path)
    constants = schema["format"]
    lines = [
        "#include <cstddef>",
        "#include <cstdint>",
        '#include "mozilla/Assertions.h"',
        "namespace js::jit {",
        "enum class AOTBlobKind : uint32_t {",
    ]
    lines += [f"  {name} = {i}," for i, name in enumerate(schema["artifacts"])]
    lines += [
        "};",
        f"inline constexpr uint32_t AOTBlobKindCount = {len(schema['artifacts'])};",
        "inline const char* AOTArtifactPrefix(AOTBlobKind kind) {",
        "  switch (kind) {",
    ]
    for name, blob in schema["artifacts"].items():
        lines.append(f'    case AOTBlobKind::{name}: return "{blob["filename_prefix"]}";')
    lines += ["  }", '  MOZ_CRASH("Invalid AOT artifact kind");', "}"]
    lines += [
        f"inline constexpr uint32_t BlobFileMagic = {constants['blob_file_magic']};",
        f"inline constexpr uint16_t BlobFileVersion = {constants['blob_file_version']};",
        "namespace image {",
    ]
    for cpp, name in [
        ("Magic", "image_magic"),
        ("Version", "image_version"),
        ("BuildIdentitySize", "build_identity_size"),
        ("Alignment", "alignment"),
        ("TextAlignment", "text_alignment"),
        ("CodeAlignment", "code_alignment"),
    ]:
        lines.append(f"inline constexpr uint32_t {cpp} = {constants[name]};")
    lines.append("}  // namespace image")
    for name, fields in schema["records"].items():
        in_image = name in ("Header", "DirectoryEntry")
        if in_image:
            lines.append("namespace image {")
        lines.append(f"struct {name} {{")
        offset = 0
        offsets = []
        for field in fields:
            kind, member = split_declaration(field, name)
            cpp, fmt = WIRE_TYPES[kind]
            size = struct.calcsize("<" + fmt)
            suffix = f"[{size}]" if fmt.endswith("s") else ""
            lines.append(f"  {cpp} {member}{suffix};")
            offsets.append(f"static_assert(offsetof({name}, {member}) == {offset});")
            offset += size
        lines += ["};", f"static_assert(sizeof({name}) == {offset});", *offsets]
        if in_image:
            lines.append("}  // namespace image")
    lines.append("}  // namespace js::jit")
    output.write(
        HEADER_TEMPLATE % {
            "includeguard": "jit_AOTImageFormatGenerated_h",
            "contents": emit_lines(lines),
        }
    )
