# Note: Generated by Claude.

import sys
import yaml
import os

def main(c_out, yaml_path):
    """
    Entry point for moz.build GeneratedFile.
    Generates the AOTPatches.h header file from the YAML patch description.
    Writes the header output to c_out.
    """
    with open(yaml_path, 'r') as f_in:
        doc = yaml.safe_load(f_in)

    # Extract metadata if present (from BaselineInterpreter.yaml)
    metadata = doc.get('metadata', {})
    has_metadata = bool(metadata)

    c_out.write("/* This Source Code Form is subject to the terms of the Mozilla Public\n")
    c_out.write(" * License, v. 2.0. If a copy of the MPL was not distributed with this\n")
    c_out.write(" * file, You can obtain one at http://mozilla.org/MPL/2.0/. */\n\n")
    c_out.write("#ifndef jit_AOTPatches_h\n")
    c_out.write("#define jit_AOTPatches_h\n\n")
    c_out.write("/* This file is generated by jit/GenerateAOTPatches.py. Do not edit! */\n\n")
    
    # Added <cstddef> for size_t
    c_out.write("#include <cstdint>\n")
    c_out.write("#include <cstddef>\n\n") 

    # 1. Extern C Declarations (Linker Symbols)
    # These match the .global symbols in your .S file
    c_out.write("extern \"C\" {\n")
    c_out.write("    extern uint8_t baseline_blob_start[];\n")
    c_out.write("    extern uint8_t baseline_blob_end[];\n")
    c_out.write("}\n\n")

    c_out.write("namespace js { namespace jit {\n\n")

    # 2. Accessor Functions
    # These provide a clean, type-safe API for the C++ runtime
    c_out.write("inline uint8_t* GetAOTBaselineBlob() {\n")
    c_out.write("    return baseline_blob_start;\n")
    c_out.write("}\n\n")

    c_out.write("inline size_t GetAOTBaselineSize() {\n")
    c_out.write("    return baseline_blob_end - baseline_blob_start;\n")
    c_out.write("}\n\n")

    # 3. Emit Baseline Interpreter Metadata (if present)
    if has_metadata:
        dispatch_offset = metadata.get('dispatch_table_offset', 0)
        opcode_offsets = metadata.get('opcode_offsets', [])
        entry_points = metadata.get('entry_points', {})

        c_out.write("// Baseline Interpreter Metadata\n")
        c_out.write(f"constexpr uint32_t kBaselineDispatchTableOffset = {dispatch_offset};\n\n")

        if opcode_offsets:
            c_out.write("constexpr uint32_t kBaselineOpcodeOffsets[] = {\n")
            for entry in opcode_offsets:
                opcode = entry.get('opcode', 0)
                offset = entry.get('offset', 0)
                c_out.write(f"    {offset}, // opcode {opcode}\n")
            c_out.write("};\n\n")

        if entry_points:
            c_out.write("// Entry point offsets for the baseline interpreter\n")
            c_out.write("struct BaselineInterpreterEntryPoints {\n")
            c_out.write(f"    uint32_t interpretOp = {entry_points.get('interpret_op', 0)};\n")
            c_out.write(f"    uint32_t interpretOpNoDebugTrap = {entry_points.get('interpret_op_no_debug_trap', 0)};\n")
            c_out.write(f"    uint32_t bailoutPrologue = {entry_points.get('bailout_prologue', 0)};\n")
            c_out.write(f"    uint32_t profilerEnterToggle = {entry_points.get('profiler_enter_toggle', 0)};\n")
            c_out.write(f"    uint32_t profilerExitToggle = {entry_points.get('profiler_exit_toggle', 0)};\n")
            c_out.write(f"    uint32_t debugTrapHandler = {entry_points.get('debug_trap_handler', 0)};\n")
            c_out.write("};\n\n")
            c_out.write("constexpr BaselineInterpreterEntryPoints kBaselineEntryPoints;\n\n")

        # Always emit debug instrumentation offsets (even if empty)
        debug_instr = metadata.get('debug_instrumentation_offsets', [])
        c_out.write("constexpr uint32_t kDebugInstrumentationOffsets[] = {\n")
        if debug_instr:
            for offset in debug_instr:
                c_out.write(f"    {offset},\n")
        else:
            c_out.write("    0  // Dummy element for empty array\n")
        c_out.write("};\n")
        c_out.write(f"constexpr size_t kDebugInstrumentationOffsetsLength = {len(debug_instr)};\n\n")

        # Always emit debug trap offsets (even if empty)
        debug_trap = metadata.get('debug_trap_offsets', [])
        c_out.write("constexpr uint32_t kDebugTrapOffsets[] = {\n")
        if debug_trap:
            for offset in debug_trap:
                c_out.write(f"    {offset},\n")
        else:
            c_out.write("    0  // Dummy element for empty array\n")
        c_out.write("};\n")
        c_out.write(f"constexpr size_t kDebugTrapOffsetsLength = {len(debug_trap)};\n\n")

        # Always emit code coverage offsets (even if empty)
        code_cov = metadata.get('code_coverage_offsets', [])
        c_out.write("constexpr uint32_t kCodeCoverageOffsets[] = {\n")
        if code_cov:
            for offset in code_cov:
                c_out.write(f"    {offset},\n")
        else:
            c_out.write("    0  // Dummy element for empty array\n")
        c_out.write("};\n")
        c_out.write(f"constexpr size_t kCodeCoverageOffsetsLength = {len(code_cov)};\n\n")

        # Always emit IC return offsets struct and array (even if empty)
        ic_returns = metadata.get('ic_return_offsets', [])
        c_out.write("struct ICReturnOffset {\n")
        c_out.write("    uint32_t offset;\n")
        c_out.write("    uint32_t opcode;\n")
        c_out.write("};\n\n")
        c_out.write("constexpr ICReturnOffset kICReturnOffsets[] = {\n")
        if ic_returns:
            for ic in ic_returns:
                offset = ic.get('offset', 0)
                opcode = ic.get('opcode', 0)
                c_out.write(f"    {{ {offset}, {opcode} }},\n")
        else:
            c_out.write("    { 0, 0 }  // Dummy element for empty array\n")
        c_out.write("};\n")
        c_out.write(f"constexpr size_t kICReturnOffsetsLength = {len(ic_returns)};\n\n")

        # Always emit CallVM offsets
        callvm = metadata.get('callvm_offsets', {})
        c_out.write("struct CallVMOffsets {\n")
        c_out.write(f"    uint32_t debugPrologueOffset = {callvm.get('debug_prologue', 0)};\n")
        c_out.write(f"    uint32_t debugEpilogueOffset = {callvm.get('debug_epilogue', 0)};\n")
        c_out.write(f"    uint32_t debugAfterYieldOffset = {callvm.get('debug_after_yield', 0)};\n")
        c_out.write("};\n\n")
        c_out.write("constexpr CallVMOffsets kCallVMOffsets;\n\n")

    # 4. Define Patch Types (only if patches exist)
    patches = doc.get('patches', [])
    if patches:
        seen_types = set(p['type'] for p in patches)
        c_out.write("enum class PatchType : uint32_t {\n")
        for t in sorted(seen_types):
            c_out.write(f"    {t},\n")
        c_out.write("};\n\n")

        # 5. Define the Struct
        c_out.write("struct BaselinePatchEntry {\n")
        c_out.write("    uint32_t offset;  // Offset from blob start\n")
        c_out.write("    PatchType type;   // What runtime value to write\n")
        c_out.write("    uint32_t count;   // How many sequential patches\n")
        c_out.write("    uint32_t stride;  // Bytes between patches (if count > 1)\n")
        c_out.write("};\n\n")

        # 6. Populate the Array
        c_out.write("constexpr BaselinePatchEntry kBaselinePatches[] = {\n")

        for p in patches:
            offset = p['offset']
            p_type = p['type']
            count = p.get('count', 1)
            stride = p.get('stride', 0)

            c_out.write(f"    {{ {offset}, PatchType::{p_type}, {count}, {stride} }},\n")

        c_out.write("};\n\n")
    c_out.write("} } // namespace js::jit\n\n")
    c_out.write("#endif // jit_AOTPatches_h\n")
