# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Parses jit/AOTBlobSchema.yaml and emits jit/AOTBlobGenerated.h with
# fields structs, decoded-payload views, and Encode/Decode helpers
# for every declared AOT blob kind.

import io

import buildconfig
import yaml
from mozbuild.preprocessor import Preprocessor

HEADER_TEMPLATE = """\
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef %(includeguard)s
#define %(includeguard)s

/* This file is generated by jit/GenerateAOTBlobFiles.py from
 * jit/AOTBlobSchema.yaml. Do not edit! */

%(contents)s

#endif // %(includeguard)s
"""


def load_yaml(yaml_path):
    pp = Preprocessor()
    pp.context.update(buildconfig.defines["ALLDEFINES"])
    pp.out = io.StringIO()
    pp.do_filter("substitution")
    pp.do_include(yaml_path)
    return yaml.safe_load(pp.out.getvalue())


PRIMITIVE_SIZE = {"u8": 1, "u16": 2, "u32": 4}
PRIMITIVE_CPP = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t"}


def field_size(f):
    if f["type"] in PRIMITIVE_SIZE:
        return PRIMITIVE_SIZE[f["type"]]
    if f["type"] == "raw":
        return int(f["size"])
    raise ValueError(f"unknown field type: {f['type']}")


def field_align(f):
    s = field_size(f)
    return s if s in (1, 2, 4, 8) else 1


def field_cpp_type(f):
    if f["type"] in PRIMITIVE_CPP:
        return PRIMITIVE_CPP[f["type"]]
    if f["type"] == "raw":
        return f["cpp_type"]
    raise ValueError(f["type"])


def struct_sizeof(fields):
    offset = 0
    max_align = 1
    for f in fields:
        a = field_align(f)
        max_align = max(max_align, a)
        offset = (offset + a - 1) & ~(a - 1)
        offset += field_size(f)
    return (offset + max_align - 1) & ~(max_align - 1)


def emit_pod_struct(name, fields, doc=None):
    lines = []
    if doc:
        for line in doc.splitlines():
            lines.append(f"// {line}" if line else "//")
    lines.append(f"struct {name} {{")
    for f in fields:
        lines.append(f"  {field_cpp_type(f)} {f['name']} = {{}};")
    lines.append("};")
    size = struct_sizeof(fields)
    lines.append(f"static_assert(sizeof({name}) == {size},")
    lines.append(
        f'              "{name} sizeof drift; edit AOTBlobSchema.yaml");'
    )
    return "\n".join(lines) + "\n"


def emit_payload_struct(name, fields_type, arrays):
    lines = [f"struct {name} {{"]
    lines.append(f"  {fields_type} fields;")
    lines.append("  mozilla::Span<const uint8_t> code;")
    for a in arrays:
        lines.append(f"  mozilla::Span<const {a['element']}> {a['name']};")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_encode(kind_name, payload_type, arrays):
    lines = [
        f"[[nodiscard]] inline bool EncodeAOTBlob_{kind_name}(",
        f"    AOTBlobWriter& blob, const {payload_type}& p) {{",
        "  if (!p.code.empty() &&",
        "      !blob.writeCode(p.code.data(), p.code.size())) {",
        "    return false;",
        "  }",
        "  if (!blob.writeFields(p.fields)) return false;",
    ]
    for a in arrays:
        lines.append(
            f"  if (!blob.writeArray(p.{a['name']})) return false;"
        )
    lines += ["  return true;", "}"]
    return "\n".join(lines) + "\n"


def emit_decode(kind_name, fields_type, payload_type, arrays):
    lines = [
        f"[[nodiscard]] inline bool DecodeAOTBlob_{kind_name}(",
        f"    AOTBlobReader& reader, {payload_type}* out) {{",
        f"  if (reader.entry()->fieldsSize != sizeof({fields_type})) {{",
        "    return false;",
        "  }",
        f"  out->fields = reader.readFields<{fields_type}>();",
        "  out->code = reader.code();",
    ]
    for a in arrays:
        lines.append(
            f"  out->{a['name']} = reader.readArray<{a['element']}>("
            f"out->fields.{a['count_from']});"
        )
    lines += ["  return true;", "}"]
    return "\n".join(lines) + "\n"


def emit_blob(kind_name, blob):
    fields_type = f"AOTFields_{kind_name}"
    payload_type = f"AOTPayload_{kind_name}"
    arrays = blob.get("arrays", [])

    out = [f"// -------- Blob: {kind_name} (kind_id={blob['kind_id']}) --------"]
    if blob.get("doc"):
        for line in blob["doc"].splitlines():
            out.append(f"// {line}" if line else "//")
    out.append("")
    out.append(emit_pod_struct(fields_type, blob["fields"]))
    out.append(emit_payload_struct(payload_type, fields_type, arrays))
    out.append(emit_encode(kind_name, payload_type, arrays))
    out.append(emit_decode(kind_name, fields_type, payload_type, arrays))
    return "\n".join(out)


def main(c_out, yaml_path):
    schema = load_yaml(yaml_path)

    body = [
        "#include <cstdint>",
        "",
        '#include "mozilla/Span.h"',
        "",
        '#include "jit/AOT.h"',
        '#include "jit/BaselineIC.h"',
        '#include "jit/BaselineJIT.h"',
        '#include "jit/CacheIR.h"',
        "",
        "namespace js::jit {",
        "",
    ]

    for name, s in (schema.get("structs") or {}).items():
        body.append(emit_pod_struct(name, s["fields"], s.get("doc")))

    for name, blob in (schema.get("blobs") or {}).items():
        body.append(emit_blob(name, blob))

    body.append("}  // namespace js::jit")

    HEADER_TEMPLATE_CTX = {
        "includeguard": "jit_AOTBlobGenerated_h",
        "contents": "\n".join(body),
    }
    c_out.write(HEADER_TEMPLATE % HEADER_TEMPLATE_CTX)
