# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Generates the C++ metadata structures and serialization helpers for each
# artifact kind declared by the image schema.

import io

import buildconfig
import yaml
from mozbuild.preprocessor import Preprocessor

HEADER_TEMPLATE = """\
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef %(includeguard)s
#define %(includeguard)s

/* Generated by jit/GenerateAOTImage.py from jit/AOTImageSchema.yaml. */

%(contents)s

#endif  // %(includeguard)s
"""


PRIMITIVE_SIZE = {"u8": 1, "u16": 2, "u32": 4}
PRIMITIVE_CPP = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t"}


def load_yaml(yaml_path):
    pp = Preprocessor()
    pp.context.update(buildconfig.defines["ALLDEFINES"])
    pp.out = io.StringIO()
    pp.do_filter("substitution")
    pp.do_include(yaml_path)
    return yaml.safe_load(pp.out.getvalue())


def field_size(f):
    if f["type"] in PRIMITIVE_SIZE:
        return PRIMITIVE_SIZE[f["type"]]
    if f["type"] == "raw":
        return int(f["size"])
    raise ValueError("unknown field type: %s" % f["type"])


def field_align(f):
    s = field_size(f)
    return s if s in (1, 2, 4, 8) else 1


def field_cpp_type(f):
    if f["type"] in PRIMITIVE_CPP:
        return PRIMITIVE_CPP[f["type"]]
    if f["type"] == "raw":
        return f["cpp_type"]
    raise ValueError(f["type"])


# Matches the compiler's aggregate layout by aligning each field naturally and
# padding the complete structure to its maximum alignment. A generated compile
# time assertion detects layout differences.
def pod_sizeof(fields):
    offset = 0
    max_align = 1
    for f in fields:
        a = field_align(f)
        max_align = max(max_align, a)
        offset = (offset + a - 1) & ~(a - 1)
        offset += field_size(f)
    return (offset + max_align - 1) & ~(max_align - 1)


def emit_lines(lines):
    return "\n".join(lines) + "\n"


def emit_doc(doc):
    if not doc:
        return []
    lines = []
    for line in doc.splitlines():
        lines.append("// " + line if line else "//")
    return lines


def emit_fields_pod(name, fields, doc=None):
    lines = emit_doc(doc)
    lines.append("struct %s {" % name)
    for f in fields:
        lines.append("  %s %s = {};" % (field_cpp_type(f), f["name"]))
    lines.append("};")
    size = pod_sizeof(fields)
    lines.append("static_assert(sizeof(%s) == %d," % (name, size))
    lines.append('              "%s size drift; edit AOTImageSchema.yaml");' % name)
    return emit_lines(lines)


def emit_view_struct(name, fields_type, arrays):
    lines = [
        "struct %s {" % name,
        "  %s fields;" % fields_type,
        "  mozilla::Span<const uint8_t> code;",
    ]
    for a in arrays:
        lines.append("  mozilla::Span<const %s> %s;" % (a["element"], a["name"]))
    lines.append("};")
    return emit_lines(lines)


def encode_field_expr(f):
    cpp = f.get("cpp_member")
    if cpp is None:
        return None
    if cpp.endswith(".length"):
        return "uint32_t(md.%s())" % cpp
    return "md.%s" % cpp


def emit_encode(kind, view_type, fields_type, fields, arrays, metadata_type):
    lines = [
        "[[nodiscard]] inline bool EncodeBlob_%s(" % kind,
        "    AOTBlobWriter& blob, const %s& md) {" % metadata_type,
        "  %s f = {};" % fields_type,
    ]
    for f in fields:
        expr = encode_field_expr(f)
        if expr is None:
            continue
        lines.append("  f.%s = %s;" % (f["name"], expr))
    lines.append("  if (!blob.writeFields(f)) return false;")
    for a in arrays:
        cpp = a.get("cpp_member")
        if cpp is None:
            continue
        lines.append(
            "  if (!blob.writeArray<%s>(md.%s.begin(), md.%s.length())) "
            "return false;" % (a["element"], cpp, cpp)
        )
    lines.append("  return true;")
    lines.append("}")
    return emit_lines(lines)


def emit_decode(kind, view_type, fields_type, fields, arrays, metadata_type):
    lines = [
        "[[nodiscard]] inline bool DecodeBlob_%s(" % kind,
        "    AOTBlobReader& reader, %s* md) {" % metadata_type,
        "  if (reader.fieldsSize() != sizeof(%s)) return false;" % fields_type,
        "  %s f = reader.readFields<%s>();" % (fields_type, fields_type),
    ]
    for f in fields:
        cpp = f.get("cpp_member")
        if cpp is None or cpp.endswith(".length"):
            continue
        lines.append("  md->%s = f.%s;" % (cpp, f["name"]))
    for a in arrays:
        cpp = a.get("cpp_member")
        if cpp is None:
            continue
        lines.append("  {")
        lines.append(
            "    auto src = reader.readArray<%s>(f.%s);"
            % (a["element"], a["count_from"])
        )
        lines.append(
            "    if (!md->%s.append(src.data(), src.size())) return false;" % cpp
        )
        lines.append("  }")
    lines.append("  return true;")
    lines.append("}")
    return emit_lines(lines)


def emit_view_reader(kind, view_type, fields_type, arrays):
    lines = [
        "inline %s ReadView_%s(AOTBlobReader& reader) {" % (view_type, kind),
        "  %s v;" % view_type,
        "  v.fields = reader.readFields<%s>();" % fields_type,
        "  v.code = reader.code();",
    ]
    for a in arrays:
        lines.append(
            "  v.%s = reader.readArray<%s>(v.fields.%s);"
            % (a["name"], a["element"], a["count_from"])
        )
    lines.append("  return v;")
    lines.append("}")
    return emit_lines(lines)


def emit_blob(kind, blob):
    fields_type = "AOTFields_%s" % kind
    view_type = "AOTView_%s" % kind
    fields = blob["fields"]
    arrays = blob.get("arrays", []) or []
    metadata_type = blob.get("metadata_type")

    out = ["// ---- Blob: %s (kind_id=%d) ----" % (kind, blob["kind_id"])]
    out.extend(emit_doc(blob.get("doc")))
    out.append("")
    out.append(emit_fields_pod(fields_type, fields))
    out.append(emit_view_struct(view_type, fields_type, arrays))
    out.append(emit_view_reader(kind, view_type, fields_type, arrays))
    if metadata_type:
        out.append(
            emit_encode(kind, view_type, fields_type, fields, arrays, metadata_type)
        )
        out.append(
            emit_decode(kind, view_type, fields_type, fields, arrays, metadata_type)
        )
    return "\n".join(out)


def emit_kind_assertions(blobs):
    # Ensures schema kind identifiers match the runtime enumeration so a rename
    # or renumbering causes a compile error.
    lines = []
    for name, blob in blobs.items():
        lines.append(
            "static_assert(uint32_t(AOTBlobKind::%s) == %d," % (name, blob["kind_id"])
        )
        lines.append(
            '              "AOTImageSchema.yaml kind_id drift for %s");' % name
        )
    return emit_lines(lines)


def main(c_out, yaml_path):
    schema = load_yaml(yaml_path)
    blobs = schema.get("blobs") or {}

    body = [
        "#include <cstdint>",
        "",
        '#include "mozilla/Span.h"',
        "",
        '#include "jit/AOTImage.h"',
        '#include "jit/BaselineJIT.h"',
        "",
        "namespace js::jit {",
        "",
        emit_kind_assertions(blobs),
    ]
    for name, blob in blobs.items():
        body.append(emit_blob(name, blob))
    body.append("}  // namespace js::jit")

    c_out.write(
        HEADER_TEMPLATE
        % {
            "includeguard": "jit_AOTImageGenerated_h",
            "contents": "\n".join(body),
        }
    )
