#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Writes an empty valid image for builds that do not have recorded artifacts. An
# image with no artifacts causes the runtime to generate code normally.

import sys

from AOTImageFormat import AOTImageFormat, align_up


def empty_image(format):
    build_identity_offset = format.header.size
    directory_offset = align_up(build_identity_offset + format.BUILD_IDENTITY_SIZE, format.ALIGNMENT)
    data_end = directory_offset  # no entries, no data
    text_offset = align_up(data_end, format.TEXT_ALIGNMENT)
    text_size = 0
    image_size = text_offset

    buf = bytearray(image_size)
    format.header.pack_into(
        buf, 0,
        magic=format.IMAGE_MAGIC,
        version=format.IMAGE_VERSION,
        reserved=0,
        blobCount=0,
        buildIdentityOffset=build_identity_offset,
        buildIdentitySize=format.BUILD_IDENTITY_SIZE,
        directoryOffset=directory_offset,
        textOffset=text_offset,
        textSize=text_size,
        imageSize=image_size,
    )
    # A zero build_identity marks an empty image.
    return bytes(buf)


def main(output, format_path):
    output.write(empty_image(AOTImageFormat.load(format_path)))
    return 0


# A zero slot table hash tells the shim there is nothing to check.
def main_relocs(output, format_path):
    lines = [
        "// Generated by GenerateEmptyAOTImage.py. Do not edit.",
        "AOT_IMAGE_SLOT_TABLE_HASH(0x00000000u)",
        f"AOT_IMAGE_CHUNK(0, {len(empty_image(AOTImageFormat.load(format_path)))})",
    ]
    output.write("\n".join(lines).encode() + b"\n")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("usage: GenerateEmptyAOTImage.py FORMAT IMAGE RELOCS", file=sys.stderr)
        sys.exit(1)
    with open(sys.argv[2], "wb") as f:
        main(f, sys.argv[1])
    with open(sys.argv[3], "wb") as f:
        main_relocs(f, sys.argv[1])
