#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Combines recorded artifacts into one image.

import argparse
import glob
import hashlib
import os
import struct
import sys

from AOTImageFormat import AOTImageFormat, align_up


class Blob:
    def __init__(self, path, format):
        with open(path, "rb") as f:
            data = f.read()
        if len(data) < 8:
            raise ValueError(f"{path}: truncated blob file")
        magic, version = struct.unpack_from("<IH", data)
        if magic != format.BLOB_FILE_MAGIC:
            raise ValueError(f"{path}: bad magic {magic:#x}")
        if version != format.BLOB_FILE_VERSION:
            raise ValueError(f"{path}: unsupported version {version}; re-record the corpus")
        if len(data) < format.blob_header.size:
            raise ValueError(f"{path}: truncated blob file")
        header = format.blob_header.unpack_from(data)
        self.kind = header["kind"]
        self.probe_hash = header["probeHash"]
        self.identity_hash = header["identityHash"]
        self.fields_size = header["fieldsSize"]
        self.arrays_size = header["arraysSize"]
        self.code_size = header["codeSize"]
        link_sites_size = header["linkSitesSize"]
        self.slot_table_hash = header["slotTableHash"]
        self.key_size = header["keySize"]
        self.build_identity = header["buildIdentity"]
        if link_sites_size % format.link_site.size:
            raise ValueError(
                f"{path}: link site table is not a whole number of entries"
            )
        expected_size = (
            format.blob_header.size
            + self.key_size
            + self.fields_size
            + self.arrays_size
            + self.code_size
            + link_sites_size
        )
        if len(data) != expected_size:
            raise ValueError(
                f"{path}: file size is {len(data)} bytes, expected {expected_size}"
            )
        p = format.blob_header.size
        self.key = data[p : p + self.key_size]
        p += self.key_size
        self.fields = data[p : p + self.fields_size]
        p += self.fields_size
        self.arrays = data[p : p + self.arrays_size]
        p += self.arrays_size
        self.code = data[p : p + self.code_size]
        p += self.code_size
        self.link_sites = []
        for offset in range(p, p + link_sites_size, format.link_site.size):
            site = format.link_site.unpack_from(data, offset)
            self.link_sites.append((site["codeOffset"], site["slot"]))
        self.source = path
        if header["reserved"] or self.kind not in format.kind_names:
            raise ValueError(f"{path}: unsupported artifact kind or flags")
        if self.key_size < 4 or self.key_size % 4:
            raise ValueError(f"{path}: malformed compilation key")
        if struct.unpack_from("<I", self.key)[0] != self.kind:
            raise ValueError(f"{path}: key kind differs from artifact kind")
        if hashlib.sha1(self.key).digest() != self.identity_hash:
            raise ValueError(f"{path}: compilation key digest mismatch")
        if not any(self.build_identity):
            raise ValueError(f"{path}: missing build identity")
        try:
            format.validate(self.kind, self.fields, self.arrays, self.key)
        except ValueError as exc:
            raise ValueError(f"{path}: {exc}") from exc
        previous = -format.LINK_SITE_WIDTH
        for offset, slot in sorted(self.link_sites):
            if offset < previous + format.LINK_SITE_WIDTH or offset + format.LINK_SITE_WIDTH > self.code_size:
                raise ValueError(f"{path}: invalid or overlapping link site")
            if any(self.code[offset:offset + format.LINK_SITE_WIDTH]):
                raise ValueError(f"{path}: nonzero link displacement")
            previous = offset


def emit_relocs(path, buf, sites, slot_table_hash, format):
    """Writes the interleaved chunk and site list the image shim expands.

    A site replaces four image bytes with a displacement the static linker
    computes, so the shim embeds the image as the runs of bytes between sites
    rather than as one blob.
    """
    lines = [
        "// Generated by PackAOTImage.py. Do not edit.",
        f"// Image SHA-256: {hashlib.sha256(buf).hexdigest()}",
        f"AOT_IMAGE_SLOT_TABLE_HASH({slot_table_hash:#010x}u)",
    ]
    cursor = 0
    for offset, slot in sites:
        if offset < cursor:
            raise ValueError(f"link site at {offset} overlaps the preceding site")
        if offset + format.LINK_SITE_WIDTH > len(buf):
            raise ValueError(f"link site at {offset} runs past the image")
        if any(buf[offset : offset + format.LINK_SITE_WIDTH]):
            raise ValueError(f"link site at {offset} does not land on a zero field")
        if offset > cursor:
            lines.append(f"AOT_IMAGE_CHUNK({cursor}, {offset - cursor})")
        lines.append(f"AOT_IMAGE_SITE({slot})")
        cursor = offset + format.LINK_SITE_WIDTH
    if cursor < len(buf):
        lines.append(f"AOT_IMAGE_CHUNK({cursor}, {len(buf) - cursor})")

    with open(path, "wb") as f:
        f.write("\n".join(lines).encode() + b"\n")


def pack(record_dir, build_identities, out_path, relocs_path, format):
    paths = sorted(glob.glob(os.path.join(record_dir, "*.aotb")))
    if not paths:
        print(f"warning: no .aotb files in {record_dir}", file=sys.stderr)
    blobs = [Blob(p, format) for p in paths]

    identities = []
    for path in build_identities:
        with open(path, "rb") as stream:
            identities.append(stream.read())
    if not identities or any(len(value) != format.BUILD_IDENTITY_SIZE for value in identities):
        raise ValueError("A destination build identity is required; build stage 1 first")
    build_identity = blobs[0].build_identity if blobs else identities[0]
    if build_identity not in identities:
        raise ValueError("Corpus belongs to another build; re-record with this build")
    unique = {}
    for blob in blobs:
        if blob.build_identity != build_identity:
            raise ValueError(f"{blob.source}: mixed build identities")
        identity = (blob.kind, blob.identity_hash)
        previous = unique.get(identity)
        if previous and (
            previous.key != blob.key or previous.fields != blob.fields
            or previous.arrays != blob.arrays or previous.code != blob.code
            or previous.link_sites != blob.link_sites
            or previous.probe_hash != blob.probe_hash
            or previous.slot_table_hash != blob.slot_table_hash
        ):
            raise ValueError(f"{blob.source}: conflicting artifact identity")
        unique[identity] = blob
    blobs = sorted(unique.values(), key=lambda blob: (blob.kind, blob.identity_hash))

    slot_table_hash = blobs[0].slot_table_hash if blobs else 0
    for b in blobs:
        if b.slot_table_hash != slot_table_hash:
            raise ValueError(
                f"{b.source}: recorded against a different slot table "
                f"({b.slot_table_hash:#x} vs {slot_table_hash:#x})"
            )

    build_identity_offset = format.header.size
    directory_offset = align_up(build_identity_offset + format.BUILD_IDENTITY_SIZE, format.ALIGNMENT)
    data_start = align_up(directory_offset + format.directory_entry.size * len(blobs), format.ALIGNMENT)

    entries = []
    cursor = data_start
    text_cursor = 0
    for b in blobs:
        text_cursor = align_up(text_cursor, format.CODE_ALIGNMENT)
        e = {
            "kind": b.kind,
            "probeHash": b.probe_hash,
            "identityHash": b.identity_hash,
            "dataOffset": cursor,
            "keySize": b.key_size,
            "fieldsSize": b.fields_size,
            "arraysSize": b.arrays_size,
            "textOffset": text_cursor,
            "textSize": b.code_size,
        }
        cursor = align_up(cursor + b.key_size + b.fields_size + b.arrays_size, format.ALIGNMENT)
        text_cursor += b.code_size
        entries.append(e)

    data_end = cursor
    text_offset = align_up(data_end, format.TEXT_ALIGNMENT)
    text_size = align_up(text_cursor, format.CODE_ALIGNMENT)
    image_size = text_offset + text_size

    buf = bytearray(image_size)

    format.header.pack_into(
        buf, 0,
        magic=format.IMAGE_MAGIC,
        version=format.IMAGE_VERSION,
        reserved=0,
        blobCount=len(blobs),
        buildIdentityOffset=build_identity_offset,
        buildIdentitySize=format.BUILD_IDENTITY_SIZE,
        directoryOffset=directory_offset,
        textOffset=text_offset,
        textSize=text_size,
        imageSize=image_size,
    )

    buf[build_identity_offset : build_identity_offset + format.BUILD_IDENTITY_SIZE] = build_identity

    sites = []
    for i, e in enumerate(entries):
        format.directory_entry.pack_into(
            buf, directory_offset + i * format.directory_entry.size, **e
        )
        b = blobs[i]
        p = e["dataOffset"]
        buf[p : p + b.key_size] = b.key
        p += b.key_size
        buf[p : p + e["fieldsSize"]] = b.fields
        buf[p + e["fieldsSize"] : p + e["fieldsSize"] + e["arraysSize"]] = b.arrays
        t = text_offset + e["textOffset"]
        buf[t : t + e["textSize"]] = b.code
        for code_offset, slot in b.link_sites:
            if code_offset + format.LINK_SITE_WIDTH > b.code_size:
                raise ValueError(f"{b.source}: link site at {code_offset} is past code")
            sites.append((t + code_offset, slot))

    sites.sort()
    emit_relocs(relocs_path, buf, sites, slot_table_hash, format)

    with open(out_path, "wb") as f:
        f.write(buf)

    print(
        f"packed {len(blobs)} blob(s) into {out_path} "
        f"({image_size} bytes, text {text_size} bytes, {len(sites)} link site(s))"
    )


def main(argv):
    p = argparse.ArgumentParser(description="Pack .aotb files into AOTImage.bin")
    p.add_argument("--format", required=True, help="Build-generated AOTImageFormat.inc")
    p.add_argument("record_dir", help="Directory of .aotb files")
    p.add_argument("out", help="Output AOTImage.bin path")
    p.add_argument(
        "--build-identity", action="append", required=True,
        help="Destination native build identity (repeat for multiple link targets)",
    )
    p.add_argument(
        "--relocs",
        default=None,
        help="Output relocation list path (default: AOTImageRelocs.inc beside out)",
    )
    args = p.parse_args(argv)
    relocs = args.relocs or os.path.join(
        os.path.dirname(args.out), "AOTImageRelocs.inc"
    )
    pack(
        args.record_dir, args.build_identity, args.out, relocs,
        AOTImageFormat.load(args.format),
    )


if __name__ == "__main__":
    main(sys.argv[1:])
